# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import autoforward_pb2 as autoforward__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in autoforward_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionControlServiceStub:
    """-----------------------------------------------------------------------------
    gRPC Services Definition
    -----------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSessions = channel.unary_unary(
                '/autoforward.SessionControlService/ListSessions',
                request_serializer=autoforward__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=autoforward__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.StartLogin = channel.unary_unary(
                '/autoforward.SessionControlService/StartLogin',
                request_serializer=autoforward__pb2.StartLoginRequest.SerializeToString,
                response_deserializer=autoforward__pb2.StartLoginResponse.FromString,
                _registered_method=True)
        self.SubmitCode = channel.unary_unary(
                '/autoforward.SessionControlService/SubmitCode',
                request_serializer=autoforward__pb2.SubmitCodeRequest.SerializeToString,
                response_deserializer=autoforward__pb2.SubmitCodeResponse.FromString,
                _registered_method=True)
        self.SubmitPassword = channel.unary_unary(
                '/autoforward.SessionControlService/SubmitPassword',
                request_serializer=autoforward__pb2.SubmitPasswordRequest.SerializeToString,
                response_deserializer=autoforward__pb2.SubmitPasswordResponse.FromString,
                _registered_method=True)
        self.BackupSession = channel.unary_unary(
                '/autoforward.SessionControlService/BackupSession',
                request_serializer=autoforward__pb2.BackupSessionRequest.SerializeToString,
                response_deserializer=autoforward__pb2.BackupSessionResponse.FromString,
                _registered_method=True)
        self.RestoreSession = channel.unary_unary(
                '/autoforward.SessionControlService/RestoreSession',
                request_serializer=autoforward__pb2.RestoreSessionRequest.SerializeToString,
                response_deserializer=autoforward__pb2.RestoreSessionResponse.FromString,
                _registered_method=True)
        self.TerminateSession = channel.unary_unary(
                '/autoforward.SessionControlService/TerminateSession',
                request_serializer=autoforward__pb2.TerminateSessionRequest.SerializeToString,
                response_deserializer=autoforward__pb2.StatusResponse.FromString,
                _registered_method=True)


class SessionControlServiceServicer:
    """-----------------------------------------------------------------------------
    gRPC Services Definition
    -----------------------------------------------------------------------------

    """

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackupSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=autoforward__pb2.ListSessionsRequest.FromString,
                    response_serializer=autoforward__pb2.ListSessionsResponse.SerializeToString,
            ),
            'StartLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.StartLogin,
                    request_deserializer=autoforward__pb2.StartLoginRequest.FromString,
                    response_serializer=autoforward__pb2.StartLoginResponse.SerializeToString,
            ),
            'SubmitCode': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitCode,
                    request_deserializer=autoforward__pb2.SubmitCodeRequest.FromString,
                    response_serializer=autoforward__pb2.SubmitCodeResponse.SerializeToString,
            ),
            'SubmitPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitPassword,
                    request_deserializer=autoforward__pb2.SubmitPasswordRequest.FromString,
                    response_serializer=autoforward__pb2.SubmitPasswordResponse.SerializeToString,
            ),
            'BackupSession': grpc.unary_unary_rpc_method_handler(
                    servicer.BackupSession,
                    request_deserializer=autoforward__pb2.BackupSessionRequest.FromString,
                    response_serializer=autoforward__pb2.BackupSessionResponse.SerializeToString,
            ),
            'RestoreSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreSession,
                    request_deserializer=autoforward__pb2.RestoreSessionRequest.FromString,
                    response_serializer=autoforward__pb2.RestoreSessionResponse.SerializeToString,
            ),
            'TerminateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateSession,
                    request_deserializer=autoforward__pb2.TerminateSessionRequest.FromString,
                    response_serializer=autoforward__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoforward.SessionControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoforward.SessionControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionControlService:
    """-----------------------------------------------------------------------------
    gRPC Services Definition
    -----------------------------------------------------------------------------

    """

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.SessionControlService/ListSessions',
            autoforward__pb2.ListSessionsRequest.SerializeToString,
            autoforward__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.SessionControlService/StartLogin',
            autoforward__pb2.StartLoginRequest.SerializeToString,
            autoforward__pb2.StartLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.SessionControlService/SubmitCode',
            autoforward__pb2.SubmitCodeRequest.SerializeToString,
            autoforward__pb2.SubmitCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.SessionControlService/SubmitPassword',
            autoforward__pb2.SubmitPasswordRequest.SerializeToString,
            autoforward__pb2.SubmitPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BackupSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.SessionControlService/BackupSession',
            autoforward__pb2.BackupSessionRequest.SerializeToString,
            autoforward__pb2.BackupSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.SessionControlService/RestoreSession',
            autoforward__pb2.RestoreSessionRequest.SerializeToString,
            autoforward__pb2.RestoreSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.SessionControlService/TerminateSession',
            autoforward__pb2.TerminateSessionRequest.SerializeToString,
            autoforward__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ForwardRuleControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRules = channel.unary_unary(
                '/autoforward.ForwardRuleControlService/ListRules',
                request_serializer=autoforward__pb2.ListRulesRequest.SerializeToString,
                response_deserializer=autoforward__pb2.ListRulesResponse.FromString,
                _registered_method=True)
        self.CreateRule = channel.unary_unary(
                '/autoforward.ForwardRuleControlService/CreateRule',
                request_serializer=autoforward__pb2.CreateRuleRequest.SerializeToString,
                response_deserializer=autoforward__pb2.ForwardRule.FromString,
                _registered_method=True)
        self.UpdateRule = channel.unary_unary(
                '/autoforward.ForwardRuleControlService/UpdateRule',
                request_serializer=autoforward__pb2.UpdateRuleRequest.SerializeToString,
                response_deserializer=autoforward__pb2.ForwardRule.FromString,
                _registered_method=True)
        self.DeleteRule = channel.unary_unary(
                '/autoforward.ForwardRuleControlService/DeleteRule',
                request_serializer=autoforward__pb2.DeleteRuleRequest.SerializeToString,
                response_deserializer=autoforward__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.TestRule = channel.unary_unary(
                '/autoforward.ForwardRuleControlService/TestRule',
                request_serializer=autoforward__pb2.TestRuleRequest.SerializeToString,
                response_deserializer=autoforward__pb2.TestRuleResponse.FromString,
                _registered_method=True)
        self.PauseRule = channel.unary_unary(
                '/autoforward.ForwardRuleControlService/PauseRule',
                request_serializer=autoforward__pb2.PauseRuleRequest.SerializeToString,
                response_deserializer=autoforward__pb2.RuleActionResponse.FromString,
                _registered_method=True)
        self.ResumeRule = channel.unary_unary(
                '/autoforward.ForwardRuleControlService/ResumeRule',
                request_serializer=autoforward__pb2.PauseRuleRequest.SerializeToString,
                response_deserializer=autoforward__pb2.RuleActionResponse.FromString,
                _registered_method=True)


class ForwardRuleControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForwardRuleControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListRules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRules,
                    request_deserializer=autoforward__pb2.ListRulesRequest.FromString,
                    response_serializer=autoforward__pb2.ListRulesResponse.SerializeToString,
            ),
            'CreateRule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRule,
                    request_deserializer=autoforward__pb2.CreateRuleRequest.FromString,
                    response_serializer=autoforward__pb2.ForwardRule.SerializeToString,
            ),
            'UpdateRule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRule,
                    request_deserializer=autoforward__pb2.UpdateRuleRequest.FromString,
                    response_serializer=autoforward__pb2.ForwardRule.SerializeToString,
            ),
            'DeleteRule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRule,
                    request_deserializer=autoforward__pb2.DeleteRuleRequest.FromString,
                    response_serializer=autoforward__pb2.StatusResponse.SerializeToString,
            ),
            'TestRule': grpc.unary_unary_rpc_method_handler(
                    servicer.TestRule,
                    request_deserializer=autoforward__pb2.TestRuleRequest.FromString,
                    response_serializer=autoforward__pb2.TestRuleResponse.SerializeToString,
            ),
            'PauseRule': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseRule,
                    request_deserializer=autoforward__pb2.PauseRuleRequest.FromString,
                    response_serializer=autoforward__pb2.RuleActionResponse.SerializeToString,
            ),
            'ResumeRule': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeRule,
                    request_deserializer=autoforward__pb2.PauseRuleRequest.FromString,
                    response_serializer=autoforward__pb2.RuleActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoforward.ForwardRuleControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoforward.ForwardRuleControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForwardRuleControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.ForwardRuleControlService/ListRules',
            autoforward__pb2.ListRulesRequest.SerializeToString,
            autoforward__pb2.ListRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.ForwardRuleControlService/CreateRule',
            autoforward__pb2.CreateRuleRequest.SerializeToString,
            autoforward__pb2.ForwardRule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.ForwardRuleControlService/UpdateRule',
            autoforward__pb2.UpdateRuleRequest.SerializeToString,
            autoforward__pb2.ForwardRule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.ForwardRuleControlService/DeleteRule',
            autoforward__pb2.DeleteRuleRequest.SerializeToString,
            autoforward__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.ForwardRuleControlService/TestRule',
            autoforward__pb2.TestRuleRequest.SerializeToString,
            autoforward__pb2.TestRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.ForwardRuleControlService/PauseRule',
            autoforward__pb2.PauseRuleRequest.SerializeToString,
            autoforward__pb2.RuleActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.ForwardRuleControlService/ResumeRule',
            autoforward__pb2.PauseRuleRequest.SerializeToString,
            autoforward__pb2.RuleActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DeliveryControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeliveryStats = channel.unary_unary(
                '/autoforward.DeliveryControlService/GetDeliveryStats',
                request_serializer=autoforward__pb2.DeliveryStatsRequest.SerializeToString,
                response_deserializer=autoforward__pb2.DeliveryStatsResponse.FromString,
                _registered_method=True)
        self.ListDeadLetter = channel.unary_unary(
                '/autoforward.DeliveryControlService/ListDeadLetter',
                request_serializer=autoforward__pb2.ListDeadLetterRequest.SerializeToString,
                response_deserializer=autoforward__pb2.ListDeadLetterResponse.FromString,
                _registered_method=True)
        self.ReplayDeadLetter = channel.unary_unary(
                '/autoforward.DeliveryControlService/ReplayDeadLetter',
                request_serializer=autoforward__pb2.ReplayDeadLetterRequest.SerializeToString,
                response_deserializer=autoforward__pb2.RuleActionResponse.FromString,
                _registered_method=True)
        self.PurgeDeadLetter = channel.unary_unary(
                '/autoforward.DeliveryControlService/PurgeDeadLetter',
                request_serializer=autoforward__pb2.PurgeDeadLetterRequest.SerializeToString,
                response_deserializer=autoforward__pb2.RuleActionResponse.FromString,
                _registered_method=True)


class DeliveryControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetDeliveryStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeadLetter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplayDeadLetter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeDeadLetter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeliveryControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeliveryStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeliveryStats,
                    request_deserializer=autoforward__pb2.DeliveryStatsRequest.FromString,
                    response_serializer=autoforward__pb2.DeliveryStatsResponse.SerializeToString,
            ),
            'ListDeadLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeadLetter,
                    request_deserializer=autoforward__pb2.ListDeadLetterRequest.FromString,
                    response_serializer=autoforward__pb2.ListDeadLetterResponse.SerializeToString,
            ),
            'ReplayDeadLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplayDeadLetter,
                    request_deserializer=autoforward__pb2.ReplayDeadLetterRequest.FromString,
                    response_serializer=autoforward__pb2.RuleActionResponse.SerializeToString,
            ),
            'PurgeDeadLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeDeadLetter,
                    request_deserializer=autoforward__pb2.PurgeDeadLetterRequest.FromString,
                    response_serializer=autoforward__pb2.RuleActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoforward.DeliveryControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoforward.DeliveryControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeliveryControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDeliveryStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.DeliveryControlService/GetDeliveryStats',
            autoforward__pb2.DeliveryStatsRequest.SerializeToString,
            autoforward__pb2.DeliveryStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeadLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.DeliveryControlService/ListDeadLetter',
            autoforward__pb2.ListDeadLetterRequest.SerializeToString,
            autoforward__pb2.ListDeadLetterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplayDeadLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.DeliveryControlService/ReplayDeadLetter',
            autoforward__pb2.ReplayDeadLetterRequest.SerializeToString,
            autoforward__pb2.RuleActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeDeadLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.DeliveryControlService/PurgeDeadLetter',
            autoforward__pb2.PurgeDeadLetterRequest.SerializeToString,
            autoforward__pb2.RuleActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FilterControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListFilters = channel.unary_unary(
                '/autoforward.FilterControlService/ListFilters',
                request_serializer=autoforward__pb2.ListFiltersRequest.SerializeToString,
                response_deserializer=autoforward__pb2.ListFiltersResponse.FromString,
                _registered_method=True)
        self.CreateFilter = channel.unary_unary(
                '/autoforward.FilterControlService/CreateFilter',
                request_serializer=autoforward__pb2.CreateFilterRequest.SerializeToString,
                response_deserializer=autoforward__pb2.FilterRule.FromString,
                _registered_method=True)
        self.UpdateFilter = channel.unary_unary(
                '/autoforward.FilterControlService/UpdateFilter',
                request_serializer=autoforward__pb2.UpdateFilterRequest.SerializeToString,
                response_deserializer=autoforward__pb2.FilterRule.FromString,
                _registered_method=True)
        self.DeleteFilter = channel.unary_unary(
                '/autoforward.FilterControlService/DeleteFilter',
                request_serializer=autoforward__pb2.DeleteFilterRequest.SerializeToString,
                response_deserializer=autoforward__pb2.StatusResponse.FromString,
                _registered_method=True)


class FilterControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilterControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFilters,
                    request_deserializer=autoforward__pb2.ListFiltersRequest.FromString,
                    response_serializer=autoforward__pb2.ListFiltersResponse.SerializeToString,
            ),
            'CreateFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFilter,
                    request_deserializer=autoforward__pb2.CreateFilterRequest.FromString,
                    response_serializer=autoforward__pb2.FilterRule.SerializeToString,
            ),
            'UpdateFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFilter,
                    request_deserializer=autoforward__pb2.UpdateFilterRequest.FromString,
                    response_serializer=autoforward__pb2.FilterRule.SerializeToString,
            ),
            'DeleteFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFilter,
                    request_deserializer=autoforward__pb2.DeleteFilterRequest.FromString,
                    response_serializer=autoforward__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoforward.FilterControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoforward.FilterControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FilterControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.FilterControlService/ListFilters',
            autoforward__pb2.ListFiltersRequest.SerializeToString,
            autoforward__pb2.ListFiltersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.FilterControlService/CreateFilter',
            autoforward__pb2.CreateFilterRequest.SerializeToString,
            autoforward__pb2.FilterRule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.FilterControlService/UpdateFilter',
            autoforward__pb2.UpdateFilterRequest.SerializeToString,
            autoforward__pb2.FilterRule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.FilterControlService/DeleteFilter',
            autoforward__pb2.DeleteFilterRequest.SerializeToString,
            autoforward__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AIControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAIConfigs = channel.unary_unary(
                '/autoforward.AIControlService/ListAIConfigs',
                request_serializer=autoforward__pb2.ListAIConfigsRequest.SerializeToString,
                response_deserializer=autoforward__pb2.ListAIConfigsResponse.FromString,
                _registered_method=True)
        self.CreateAIConfig = channel.unary_unary(
                '/autoforward.AIControlService/CreateAIConfig',
                request_serializer=autoforward__pb2.CreateAIConfigRequest.SerializeToString,
                response_deserializer=autoforward__pb2.AIConfig.FromString,
                _registered_method=True)
        self.UpdateAIConfig = channel.unary_unary(
                '/autoforward.AIControlService/UpdateAIConfig',
                request_serializer=autoforward__pb2.UpdateAIConfigRequest.SerializeToString,
                response_deserializer=autoforward__pb2.AIConfig.FromString,
                _registered_method=True)
        self.DeleteAIConfig = channel.unary_unary(
                '/autoforward.AIControlService/DeleteAIConfig',
                request_serializer=autoforward__pb2.DeleteAIConfigRequest.SerializeToString,
                response_deserializer=autoforward__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.TestAIRewrite = channel.unary_unary(
                '/autoforward.AIControlService/TestAIRewrite',
                request_serializer=autoforward__pb2.TestAIRewriteRequest.SerializeToString,
                response_deserializer=autoforward__pb2.TestAIRewriteResponse.FromString,
                _registered_method=True)


class AIControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListAIConfigs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAIConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAIConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAIConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestAIRewrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAIConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAIConfigs,
                    request_deserializer=autoforward__pb2.ListAIConfigsRequest.FromString,
                    response_serializer=autoforward__pb2.ListAIConfigsResponse.SerializeToString,
            ),
            'CreateAIConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAIConfig,
                    request_deserializer=autoforward__pb2.CreateAIConfigRequest.FromString,
                    response_serializer=autoforward__pb2.AIConfig.SerializeToString,
            ),
            'UpdateAIConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAIConfig,
                    request_deserializer=autoforward__pb2.UpdateAIConfigRequest.FromString,
                    response_serializer=autoforward__pb2.AIConfig.SerializeToString,
            ),
            'DeleteAIConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAIConfig,
                    request_deserializer=autoforward__pb2.DeleteAIConfigRequest.FromString,
                    response_serializer=autoforward__pb2.StatusResponse.SerializeToString,
            ),
            'TestAIRewrite': grpc.unary_unary_rpc_method_handler(
                    servicer.TestAIRewrite,
                    request_deserializer=autoforward__pb2.TestAIRewriteRequest.FromString,
                    response_serializer=autoforward__pb2.TestAIRewriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoforward.AIControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoforward.AIControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAIConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.AIControlService/ListAIConfigs',
            autoforward__pb2.ListAIConfigsRequest.SerializeToString,
            autoforward__pb2.ListAIConfigsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAIConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.AIControlService/CreateAIConfig',
            autoforward__pb2.CreateAIConfigRequest.SerializeToString,
            autoforward__pb2.AIConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAIConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.AIControlService/UpdateAIConfig',
            autoforward__pb2.UpdateAIConfigRequest.SerializeToString,
            autoforward__pb2.AIConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAIConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.AIControlService/DeleteAIConfig',
            autoforward__pb2.DeleteAIConfigRequest.SerializeToString,
            autoforward__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestAIRewrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.AIControlService/TestAIRewrite',
            autoforward__pb2.TestAIRewriteRequest.SerializeToString,
            autoforward__pb2.TestAIRewriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SystemStatusControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemStats = channel.unary_unary(
                '/autoforward.SystemStatusControlService/GetSystemStats',
                request_serializer=autoforward__pb2.SystemStatsRequest.SerializeToString,
                response_deserializer=autoforward__pb2.SystemStatsResponse.FromString,
                _registered_method=True)


class SystemStatusControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetSystemStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemStatusControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStats,
                    request_deserializer=autoforward__pb2.SystemStatsRequest.FromString,
                    response_serializer=autoforward__pb2.SystemStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoforward.SystemStatusControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoforward.SystemStatusControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemStatusControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSystemStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.SystemStatusControlService/GetSystemStats',
            autoforward__pb2.SystemStatsRequest.SerializeToString,
            autoforward__pb2.SystemStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LogControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Log = channel.unary_unary(
                '/autoforward.LogControlService/Log',
                request_serializer=autoforward__pb2.LogRequest.SerializeToString,
                response_deserializer=autoforward__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.QueryLogs = channel.unary_unary(
                '/autoforward.LogControlService/QueryLogs',
                request_serializer=autoforward__pb2.QueryLogsRequest.SerializeToString,
                response_deserializer=autoforward__pb2.QueryLogsResponse.FromString,
                _registered_method=True)
        self.LogStats = channel.unary_unary(
                '/autoforward.LogControlService/LogStats',
                request_serializer=autoforward__pb2.LogStatsRequest.SerializeToString,
                response_deserializer=autoforward__pb2.LogStatsResponse.FromString,
                _registered_method=True)


class LogControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Log': grpc.unary_unary_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=autoforward__pb2.LogRequest.FromString,
                    response_serializer=autoforward__pb2.StatusResponse.SerializeToString,
            ),
            'QueryLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLogs,
                    request_deserializer=autoforward__pb2.QueryLogsRequest.FromString,
                    response_serializer=autoforward__pb2.QueryLogsResponse.SerializeToString,
            ),
            'LogStats': grpc.unary_unary_rpc_method_handler(
                    servicer.LogStats,
                    request_deserializer=autoforward__pb2.LogStatsRequest.FromString,
                    response_serializer=autoforward__pb2.LogStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoforward.LogControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoforward.LogControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.LogControlService/Log',
            autoforward__pb2.LogRequest.SerializeToString,
            autoforward__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.LogControlService/QueryLogs',
            autoforward__pb2.QueryLogsRequest.SerializeToString,
            autoforward__pb2.QueryLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.LogControlService/LogStats',
            autoforward__pb2.LogStatsRequest.SerializeToString,
            autoforward__pb2.LogStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AccountControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAccount = channel.unary_unary(
                '/autoforward.AccountControlService/RegisterAccount',
                request_serializer=autoforward__pb2.RegisterAccountRequest.SerializeToString,
                response_deserializer=autoforward__pb2.RegisterAccountResponse.FromString,
                _registered_method=True)
        self.LoginAccount = channel.unary_unary(
                '/autoforward.AccountControlService/LoginAccount',
                request_serializer=autoforward__pb2.LoginAccountRequest.SerializeToString,
                response_deserializer=autoforward__pb2.LoginAccountResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/autoforward.AccountControlService/ValidateToken',
                request_serializer=autoforward__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=autoforward__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)
        self.IssueWebToken = channel.unary_unary(
                '/autoforward.AccountControlService/IssueWebToken',
                request_serializer=autoforward__pb2.IssueWebTokenRequest.SerializeToString,
                response_deserializer=autoforward__pb2.LoginAccountResponse.FromString,
                _registered_method=True)
        self.ChangePassword = channel.unary_unary(
                '/autoforward.AccountControlService/ChangePassword',
                request_serializer=autoforward__pb2.ChangePasswordRequest.SerializeToString,
                response_deserializer=autoforward__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetAccount = channel.unary_unary(
                '/autoforward.AccountControlService/GetAccount',
                request_serializer=autoforward__pb2.GetAccountRequest.SerializeToString,
                response_deserializer=autoforward__pb2.WebAccount.FromString,
                _registered_method=True)


class AccountControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueWebToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAccount,
                    request_deserializer=autoforward__pb2.RegisterAccountRequest.FromString,
                    response_serializer=autoforward__pb2.RegisterAccountResponse.SerializeToString,
            ),
            'LoginAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginAccount,
                    request_deserializer=autoforward__pb2.LoginAccountRequest.FromString,
                    response_serializer=autoforward__pb2.LoginAccountResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=autoforward__pb2.ValidateTokenRequest.FromString,
                    response_serializer=autoforward__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'IssueWebToken': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueWebToken,
                    request_deserializer=autoforward__pb2.IssueWebTokenRequest.FromString,
                    response_serializer=autoforward__pb2.LoginAccountResponse.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=autoforward__pb2.ChangePasswordRequest.FromString,
                    response_serializer=autoforward__pb2.StatusResponse.SerializeToString,
            ),
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=autoforward__pb2.GetAccountRequest.FromString,
                    response_serializer=autoforward__pb2.WebAccount.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoforward.AccountControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoforward.AccountControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.AccountControlService/RegisterAccount',
            autoforward__pb2.RegisterAccountRequest.SerializeToString,
            autoforward__pb2.RegisterAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.AccountControlService/LoginAccount',
            autoforward__pb2.LoginAccountRequest.SerializeToString,
            autoforward__pb2.LoginAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.AccountControlService/ValidateToken',
            autoforward__pb2.ValidateTokenRequest.SerializeToString,
            autoforward__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssueWebToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.AccountControlService/IssueWebToken',
            autoforward__pb2.IssueWebTokenRequest.SerializeToString,
            autoforward__pb2.LoginAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.AccountControlService/ChangePassword',
            autoforward__pb2.ChangePasswordRequest.SerializeToString,
            autoforward__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforward.AccountControlService/GetAccount',
            autoforward__pb2.GetAccountRequest.SerializeToString,
            autoforward__pb2.WebAccount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
