// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.31.1
// source: autoforward.proto

package autoforwardpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SessionControlService_ListSessions_FullMethodName     = "/autoforward.SessionControlService/ListSessions"
	SessionControlService_StartLogin_FullMethodName       = "/autoforward.SessionControlService/StartLogin"
	SessionControlService_SubmitCode_FullMethodName       = "/autoforward.SessionControlService/SubmitCode"
	SessionControlService_SubmitPassword_FullMethodName   = "/autoforward.SessionControlService/SubmitPassword"
	SessionControlService_BackupSession_FullMethodName    = "/autoforward.SessionControlService/BackupSession"
	SessionControlService_RestoreSession_FullMethodName   = "/autoforward.SessionControlService/RestoreSession"
	SessionControlService_TerminateSession_FullMethodName = "/autoforward.SessionControlService/TerminateSession"
)

// SessionControlServiceClient is the client API for SessionControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionControlServiceClient interface {
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error)
	SubmitCode(ctx context.Context, in *SubmitCodeRequest, opts ...grpc.CallOption) (*SubmitCodeResponse, error)
	SubmitPassword(ctx context.Context, in *SubmitPasswordRequest, opts ...grpc.CallOption) (*SubmitPasswordResponse, error)
	BackupSession(ctx context.Context, in *BackupSessionRequest, opts ...grpc.CallOption) (*BackupSessionResponse, error)
	RestoreSession(ctx context.Context, in *RestoreSessionRequest, opts ...grpc.CallOption) (*RestoreSessionResponse, error)
	TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type sessionControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionControlServiceClient(cc grpc.ClientConnInterface) SessionControlServiceClient {
	return &sessionControlServiceClient{cc}
}

func (c *sessionControlServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, SessionControlService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLoginResponse)
	err := c.cc.Invoke(ctx, SessionControlService_StartLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) SubmitCode(ctx context.Context, in *SubmitCodeRequest, opts ...grpc.CallOption) (*SubmitCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCodeResponse)
	err := c.cc.Invoke(ctx, SessionControlService_SubmitCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) SubmitPassword(ctx context.Context, in *SubmitPasswordRequest, opts ...grpc.CallOption) (*SubmitPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitPasswordResponse)
	err := c.cc.Invoke(ctx, SessionControlService_SubmitPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) BackupSession(ctx context.Context, in *BackupSessionRequest, opts ...grpc.CallOption) (*BackupSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupSessionResponse)
	err := c.cc.Invoke(ctx, SessionControlService_BackupSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) RestoreSession(ctx context.Context, in *RestoreSessionRequest, opts ...grpc.CallOption) (*RestoreSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreSessionResponse)
	err := c.cc.Invoke(ctx, SessionControlService_RestoreSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, SessionControlService_TerminateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionControlServiceServer is the server API for SessionControlService service.
// All implementations must embed UnimplementedSessionControlServiceServer
// for forward compatibility
type SessionControlServiceServer interface {
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error)
	SubmitCode(context.Context, *SubmitCodeRequest) (*SubmitCodeResponse, error)
	SubmitPassword(context.Context, *SubmitPasswordRequest) (*SubmitPasswordResponse, error)
	BackupSession(context.Context, *BackupSessionRequest) (*BackupSessionResponse, error)
	RestoreSession(context.Context, *RestoreSessionRequest) (*RestoreSessionResponse, error)
	TerminateSession(context.Context, *TerminateSessionRequest) (*StatusResponse, error)
	mustEmbedUnimplementedSessionControlServiceServer()
}

// UnimplementedSessionControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSessionControlServiceServer struct {
}

func (UnimplementedSessionControlServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSessionControlServiceServer) StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLogin not implemented")
}
func (UnimplementedSessionControlServiceServer) SubmitCode(context.Context, *SubmitCodeRequest) (*SubmitCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitCode not implemented")
}
func (UnimplementedSessionControlServiceServer) SubmitPassword(context.Context, *SubmitPasswordRequest) (*SubmitPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPassword not implemented")
}
func (UnimplementedSessionControlServiceServer) BackupSession(context.Context, *BackupSessionRequest) (*BackupSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupSession not implemented")
}
func (UnimplementedSessionControlServiceServer) RestoreSession(context.Context, *RestoreSessionRequest) (*RestoreSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreSession not implemented")
}
func (UnimplementedSessionControlServiceServer) TerminateSession(context.Context, *TerminateSessionRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateSession not implemented")
}
func (UnimplementedSessionControlServiceServer) mustEmbedUnimplementedSessionControlServiceServer() {}

// UnsafeSessionControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionControlServiceServer will
// result in compilation errors.
type UnsafeSessionControlServiceServer interface {
	mustEmbedUnimplementedSessionControlServiceServer()
}

func RegisterSessionControlServiceServer(s grpc.ServiceRegistrar, srv SessionControlServiceServer) {
	s.RegisterService(&SessionControlService_ServiceDesc, srv)
}

func _SessionControlService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_StartLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).StartLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_StartLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).StartLogin(ctx, req.(*StartLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_SubmitCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).SubmitCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_SubmitCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).SubmitCode(ctx, req.(*SubmitCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_SubmitPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).SubmitPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_SubmitPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).SubmitPassword(ctx, req.(*SubmitPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_BackupSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).BackupSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_BackupSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).BackupSession(ctx, req.(*BackupSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_RestoreSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).RestoreSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_RestoreSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).RestoreSession(ctx, req.(*RestoreSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_TerminateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).TerminateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_TerminateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).TerminateSession(ctx, req.(*TerminateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionControlService_ServiceDesc is the grpc.ServiceDesc for SessionControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.SessionControlService",
	HandlerType: (*SessionControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSessions",
			Handler:    _SessionControlService_ListSessions_Handler,
		},
		{
			MethodName: "StartLogin",
			Handler:    _SessionControlService_StartLogin_Handler,
		},
		{
			MethodName: "SubmitCode",
			Handler:    _SessionControlService_SubmitCode_Handler,
		},
		{
			MethodName: "SubmitPassword",
			Handler:    _SessionControlService_SubmitPassword_Handler,
		},
		{
			MethodName: "BackupSession",
			Handler:    _SessionControlService_BackupSession_Handler,
		},
		{
			MethodName: "RestoreSession",
			Handler:    _SessionControlService_RestoreSession_Handler,
		},
		{
			MethodName: "TerminateSession",
			Handler:    _SessionControlService_TerminateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}

const (
	ForwardRuleControlService_ListRules_FullMethodName  = "/autoforward.ForwardRuleControlService/ListRules"
	ForwardRuleControlService_CreateRule_FullMethodName = "/autoforward.ForwardRuleControlService/CreateRule"
	ForwardRuleControlService_UpdateRule_FullMethodName = "/autoforward.ForwardRuleControlService/UpdateRule"
	ForwardRuleControlService_DeleteRule_FullMethodName = "/autoforward.ForwardRuleControlService/DeleteRule"
	ForwardRuleControlService_TestRule_FullMethodName   = "/autoforward.ForwardRuleControlService/TestRule"
	ForwardRuleControlService_PauseRule_FullMethodName  = "/autoforward.ForwardRuleControlService/PauseRule"
	ForwardRuleControlService_ResumeRule_FullMethodName = "/autoforward.ForwardRuleControlService/ResumeRule"
)

// ForwardRuleControlServiceClient is the client API for ForwardRuleControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForwardRuleControlServiceClient interface {
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*ForwardRule, error)
	UpdateRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*ForwardRule, error)
	DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	TestRule(ctx context.Context, in *TestRuleRequest, opts ...grpc.CallOption) (*TestRuleResponse, error)
	PauseRule(ctx context.Context, in *PauseRuleRequest, opts ...grpc.CallOption) (*RuleActionResponse, error)
	ResumeRule(ctx context.Context, in *PauseRuleRequest, opts ...grpc.CallOption) (*RuleActionResponse, error)
}

type forwardRuleControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardRuleControlServiceClient(cc grpc.ClientConnInterface) ForwardRuleControlServiceClient {
	return &forwardRuleControlServiceClient{cc}
}

func (c *forwardRuleControlServiceClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, ForwardRuleControlService_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardRuleControlServiceClient) CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*ForwardRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardRule)
	err := c.cc.Invoke(ctx, ForwardRuleControlService_CreateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardRuleControlServiceClient) UpdateRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*ForwardRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardRule)
	err := c.cc.Invoke(ctx, ForwardRuleControlService_UpdateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardRuleControlServiceClient) DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ForwardRuleControlService_DeleteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardRuleControlServiceClient) TestRule(ctx context.Context, in *TestRuleRequest, opts ...grpc.CallOption) (*TestRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestRuleResponse)
	err := c.cc.Invoke(ctx, ForwardRuleControlService_TestRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardRuleControlServiceClient) PauseRule(ctx context.Context, in *PauseRuleRequest, opts ...grpc.CallOption) (*RuleActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleActionResponse)
	err := c.cc.Invoke(ctx, ForwardRuleControlService_PauseRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardRuleControlServiceClient) ResumeRule(ctx context.Context, in *PauseRuleRequest, opts ...grpc.CallOption) (*RuleActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleActionResponse)
	err := c.cc.Invoke(ctx, ForwardRuleControlService_ResumeRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardRuleControlServiceServer is the server API for ForwardRuleControlService service.
// All implementations must embed UnimplementedForwardRuleControlServiceServer
// for forward compatibility
type ForwardRuleControlServiceServer interface {
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	CreateRule(context.Context, *CreateRuleRequest) (*ForwardRule, error)
	UpdateRule(context.Context, *UpdateRuleRequest) (*ForwardRule, error)
	DeleteRule(context.Context, *DeleteRuleRequest) (*StatusResponse, error)
	TestRule(context.Context, *TestRuleRequest) (*TestRuleResponse, error)
	PauseRule(context.Context, *PauseRuleRequest) (*RuleActionResponse, error)
	ResumeRule(context.Context, *PauseRuleRequest) (*RuleActionResponse, error)
	mustEmbedUnimplementedForwardRuleControlServiceServer()
}

// UnimplementedForwardRuleControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedForwardRuleControlServiceServer struct {
}

func (UnimplementedForwardRuleControlServiceServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedForwardRuleControlServiceServer) CreateRule(context.Context, *CreateRuleRequest) (*ForwardRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRule not implemented")
}
func (UnimplementedForwardRuleControlServiceServer) UpdateRule(context.Context, *UpdateRuleRequest) (*ForwardRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRule not implemented")
}
func (UnimplementedForwardRuleControlServiceServer) DeleteRule(context.Context, *DeleteRuleRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRule not implemented")
}
func (UnimplementedForwardRuleControlServiceServer) TestRule(context.Context, *TestRuleRequest) (*TestRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestRule not implemented")
}
func (UnimplementedForwardRuleControlServiceServer) PauseRule(context.Context, *PauseRuleRequest) (*RuleActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseRule not implemented")
}
func (UnimplementedForwardRuleControlServiceServer) ResumeRule(context.Context, *PauseRuleRequest) (*RuleActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeRule not implemented")
}
func (UnimplementedForwardRuleControlServiceServer) mustEmbedUnimplementedForwardRuleControlServiceServer() {
}

// UnsafeForwardRuleControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwardRuleControlServiceServer will
// result in compilation errors.
type UnsafeForwardRuleControlServiceServer interface {
	mustEmbedUnimplementedForwardRuleControlServiceServer()
}

func RegisterForwardRuleControlServiceServer(s grpc.ServiceRegistrar, srv ForwardRuleControlServiceServer) {
	s.RegisterService(&ForwardRuleControlService_ServiceDesc, srv)
}

func _ForwardRuleControlService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardRuleControlServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardRuleControlService_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardRuleControlServiceServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardRuleControlService_CreateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardRuleControlServiceServer).CreateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardRuleControlService_CreateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardRuleControlServiceServer).CreateRule(ctx, req.(*CreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardRuleControlService_UpdateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardRuleControlServiceServer).UpdateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardRuleControlService_UpdateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardRuleControlServiceServer).UpdateRule(ctx, req.(*UpdateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardRuleControlService_DeleteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardRuleControlServiceServer).DeleteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardRuleControlService_DeleteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardRuleControlServiceServer).DeleteRule(ctx, req.(*DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardRuleControlService_TestRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardRuleControlServiceServer).TestRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardRuleControlService_TestRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardRuleControlServiceServer).TestRule(ctx, req.(*TestRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardRuleControlService_PauseRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardRuleControlServiceServer).PauseRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardRuleControlService_PauseRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardRuleControlServiceServer).PauseRule(ctx, req.(*PauseRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardRuleControlService_ResumeRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardRuleControlServiceServer).ResumeRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardRuleControlService_ResumeRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardRuleControlServiceServer).ResumeRule(ctx, req.(*PauseRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForwardRuleControlService_ServiceDesc is the grpc.ServiceDesc for ForwardRuleControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwardRuleControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.ForwardRuleControlService",
	HandlerType: (*ForwardRuleControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRules",
			Handler:    _ForwardRuleControlService_ListRules_Handler,
		},
		{
			MethodName: "CreateRule",
			Handler:    _ForwardRuleControlService_CreateRule_Handler,
		},
		{
			MethodName: "UpdateRule",
			Handler:    _ForwardRuleControlService_UpdateRule_Handler,
		},
		{
			MethodName: "DeleteRule",
			Handler:    _ForwardRuleControlService_DeleteRule_Handler,
		},
		{
			MethodName: "TestRule",
			Handler:    _ForwardRuleControlService_TestRule_Handler,
		},
		{
			MethodName: "PauseRule",
			Handler:    _ForwardRuleControlService_PauseRule_Handler,
		},
		{
			MethodName: "ResumeRule",
			Handler:    _ForwardRuleControlService_ResumeRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}

const (
	DeliveryControlService_GetDeliveryStats_FullMethodName = "/autoforward.DeliveryControlService/GetDeliveryStats"
	DeliveryControlService_ListDeadLetter_FullMethodName   = "/autoforward.DeliveryControlService/ListDeadLetter"
	DeliveryControlService_ReplayDeadLetter_FullMethodName = "/autoforward.DeliveryControlService/ReplayDeadLetter"
	DeliveryControlService_PurgeDeadLetter_FullMethodName  = "/autoforward.DeliveryControlService/PurgeDeadLetter"
)

// DeliveryControlServiceClient is the client API for DeliveryControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryControlServiceClient interface {
	GetDeliveryStats(ctx context.Context, in *DeliveryStatsRequest, opts ...grpc.CallOption) (*DeliveryStatsResponse, error)
	ListDeadLetter(ctx context.Context, in *ListDeadLetterRequest, opts ...grpc.CallOption) (*ListDeadLetterResponse, error)
	ReplayDeadLetter(ctx context.Context, in *ReplayDeadLetterRequest, opts ...grpc.CallOption) (*RuleActionResponse, error)
	PurgeDeadLetter(ctx context.Context, in *PurgeDeadLetterRequest, opts ...grpc.CallOption) (*RuleActionResponse, error)
}

type deliveryControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryControlServiceClient(cc grpc.ClientConnInterface) DeliveryControlServiceClient {
	return &deliveryControlServiceClient{cc}
}

func (c *deliveryControlServiceClient) GetDeliveryStats(ctx context.Context, in *DeliveryStatsRequest, opts ...grpc.CallOption) (*DeliveryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryStatsResponse)
	err := c.cc.Invoke(ctx, DeliveryControlService_GetDeliveryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryControlServiceClient) ListDeadLetter(ctx context.Context, in *ListDeadLetterRequest, opts ...grpc.CallOption) (*ListDeadLetterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeadLetterResponse)
	err := c.cc.Invoke(ctx, DeliveryControlService_ListDeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryControlServiceClient) ReplayDeadLetter(ctx context.Context, in *ReplayDeadLetterRequest, opts ...grpc.CallOption) (*RuleActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleActionResponse)
	err := c.cc.Invoke(ctx, DeliveryControlService_ReplayDeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryControlServiceClient) PurgeDeadLetter(ctx context.Context, in *PurgeDeadLetterRequest, opts ...grpc.CallOption) (*RuleActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleActionResponse)
	err := c.cc.Invoke(ctx, DeliveryControlService_PurgeDeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryControlServiceServer is the server API for DeliveryControlService service.
// All implementations must embed UnimplementedDeliveryControlServiceServer
// for forward compatibility
type DeliveryControlServiceServer interface {
	GetDeliveryStats(context.Context, *DeliveryStatsRequest) (*DeliveryStatsResponse, error)
	ListDeadLetter(context.Context, *ListDeadLetterRequest) (*ListDeadLetterResponse, error)
	ReplayDeadLetter(context.Context, *ReplayDeadLetterRequest) (*RuleActionResponse, error)
	PurgeDeadLetter(context.Context, *PurgeDeadLetterRequest) (*RuleActionResponse, error)
	mustEmbedUnimplementedDeliveryControlServiceServer()
}

// UnimplementedDeliveryControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeliveryControlServiceServer struct {
}

func (UnimplementedDeliveryControlServiceServer) GetDeliveryStats(context.Context, *DeliveryStatsRequest) (*DeliveryStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveryStats not implemented")
}
func (UnimplementedDeliveryControlServiceServer) ListDeadLetter(context.Context, *ListDeadLetterRequest) (*ListDeadLetterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeadLetter not implemented")
}
func (UnimplementedDeliveryControlServiceServer) ReplayDeadLetter(context.Context, *ReplayDeadLetterRequest) (*RuleActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplayDeadLetter not implemented")
}
func (UnimplementedDeliveryControlServiceServer) PurgeDeadLetter(context.Context, *PurgeDeadLetterRequest) (*RuleActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeDeadLetter not implemented")
}
func (UnimplementedDeliveryControlServiceServer) mustEmbedUnimplementedDeliveryControlServiceServer() {
}

// UnsafeDeliveryControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryControlServiceServer will
// result in compilation errors.
type UnsafeDeliveryControlServiceServer interface {
	mustEmbedUnimplementedDeliveryControlServiceServer()
}

func RegisterDeliveryControlServiceServer(s grpc.ServiceRegistrar, srv DeliveryControlServiceServer) {
	s.RegisterService(&DeliveryControlService_ServiceDesc, srv)
}

func _DeliveryControlService_GetDeliveryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryControlServiceServer).GetDeliveryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryControlService_GetDeliveryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryControlServiceServer).GetDeliveryStats(ctx, req.(*DeliveryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryControlService_ListDeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryControlServiceServer).ListDeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryControlService_ListDeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryControlServiceServer).ListDeadLetter(ctx, req.(*ListDeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryControlService_ReplayDeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayDeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryControlServiceServer).ReplayDeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryControlService_ReplayDeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryControlServiceServer).ReplayDeadLetter(ctx, req.(*ReplayDeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryControlService_PurgeDeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeDeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryControlServiceServer).PurgeDeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryControlService_PurgeDeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryControlServiceServer).PurgeDeadLetter(ctx, req.(*PurgeDeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryControlService_ServiceDesc is the grpc.ServiceDesc for DeliveryControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.DeliveryControlService",
	HandlerType: (*DeliveryControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeliveryStats",
			Handler:    _DeliveryControlService_GetDeliveryStats_Handler,
		},
		{
			MethodName: "ListDeadLetter",
			Handler:    _DeliveryControlService_ListDeadLetter_Handler,
		},
		{
			MethodName: "ReplayDeadLetter",
			Handler:    _DeliveryControlService_ReplayDeadLetter_Handler,
		},
		{
			MethodName: "PurgeDeadLetter",
			Handler:    _DeliveryControlService_PurgeDeadLetter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}

const (
	FilterControlService_ListFilters_FullMethodName  = "/autoforward.FilterControlService/ListFilters"
	FilterControlService_CreateFilter_FullMethodName = "/autoforward.FilterControlService/CreateFilter"
	FilterControlService_UpdateFilter_FullMethodName = "/autoforward.FilterControlService/UpdateFilter"
	FilterControlService_DeleteFilter_FullMethodName = "/autoforward.FilterControlService/DeleteFilter"
)

// FilterControlServiceClient is the client API for FilterControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilterControlServiceClient interface {
	ListFilters(ctx context.Context, in *ListFiltersRequest, opts ...grpc.CallOption) (*ListFiltersResponse, error)
	CreateFilter(ctx context.Context, in *CreateFilterRequest, opts ...grpc.CallOption) (*FilterRule, error)
	UpdateFilter(ctx context.Context, in *UpdateFilterRequest, opts ...grpc.CallOption) (*FilterRule, error)
	DeleteFilter(ctx context.Context, in *DeleteFilterRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type filterControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilterControlServiceClient(cc grpc.ClientConnInterface) FilterControlServiceClient {
	return &filterControlServiceClient{cc}
}

func (c *filterControlServiceClient) ListFilters(ctx context.Context, in *ListFiltersRequest, opts ...grpc.CallOption) (*ListFiltersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFiltersResponse)
	err := c.cc.Invoke(ctx, FilterControlService_ListFilters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filterControlServiceClient) CreateFilter(ctx context.Context, in *CreateFilterRequest, opts ...grpc.CallOption) (*FilterRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterRule)
	err := c.cc.Invoke(ctx, FilterControlService_CreateFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filterControlServiceClient) UpdateFilter(ctx context.Context, in *UpdateFilterRequest, opts ...grpc.CallOption) (*FilterRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterRule)
	err := c.cc.Invoke(ctx, FilterControlService_UpdateFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filterControlServiceClient) DeleteFilter(ctx context.Context, in *DeleteFilterRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, FilterControlService_DeleteFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilterControlServiceServer is the server API for FilterControlService service.
// All implementations must embed UnimplementedFilterControlServiceServer
// for forward compatibility
type FilterControlServiceServer interface {
	ListFilters(context.Context, *ListFiltersRequest) (*ListFiltersResponse, error)
	CreateFilter(context.Context, *CreateFilterRequest) (*FilterRule, error)
	UpdateFilter(context.Context, *UpdateFilterRequest) (*FilterRule, error)
	DeleteFilter(context.Context, *DeleteFilterRequest) (*StatusResponse, error)
	mustEmbedUnimplementedFilterControlServiceServer()
}

// UnimplementedFilterControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFilterControlServiceServer struct {
}

func (UnimplementedFilterControlServiceServer) ListFilters(context.Context, *ListFiltersRequest) (*ListFiltersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFilters not implemented")
}
func (UnimplementedFilterControlServiceServer) CreateFilter(context.Context, *CreateFilterRequest) (*FilterRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFilter not implemented")
}
func (UnimplementedFilterControlServiceServer) UpdateFilter(context.Context, *UpdateFilterRequest) (*FilterRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFilter not implemented")
}
func (UnimplementedFilterControlServiceServer) DeleteFilter(context.Context, *DeleteFilterRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFilter not implemented")
}
func (UnimplementedFilterControlServiceServer) mustEmbedUnimplementedFilterControlServiceServer() {}

// UnsafeFilterControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilterControlServiceServer will
// result in compilation errors.
type UnsafeFilterControlServiceServer interface {
	mustEmbedUnimplementedFilterControlServiceServer()
}

func RegisterFilterControlServiceServer(s grpc.ServiceRegistrar, srv FilterControlServiceServer) {
	s.RegisterService(&FilterControlService_ServiceDesc, srv)
}

func _FilterControlService_ListFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFiltersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterControlServiceServer).ListFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterControlService_ListFilters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterControlServiceServer).ListFilters(ctx, req.(*ListFiltersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilterControlService_CreateFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterControlServiceServer).CreateFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterControlService_CreateFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterControlServiceServer).CreateFilter(ctx, req.(*CreateFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilterControlService_UpdateFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterControlServiceServer).UpdateFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterControlService_UpdateFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterControlServiceServer).UpdateFilter(ctx, req.(*UpdateFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilterControlService_DeleteFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterControlServiceServer).DeleteFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterControlService_DeleteFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterControlServiceServer).DeleteFilter(ctx, req.(*DeleteFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilterControlService_ServiceDesc is the grpc.ServiceDesc for FilterControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilterControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.FilterControlService",
	HandlerType: (*FilterControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFilters",
			Handler:    _FilterControlService_ListFilters_Handler,
		},
		{
			MethodName: "CreateFilter",
			Handler:    _FilterControlService_CreateFilter_Handler,
		},
		{
			MethodName: "UpdateFilter",
			Handler:    _FilterControlService_UpdateFilter_Handler,
		},
		{
			MethodName: "DeleteFilter",
			Handler:    _FilterControlService_DeleteFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}

const (
	AIControlService_ListAIConfigs_FullMethodName  = "/autoforward.AIControlService/ListAIConfigs"
	AIControlService_CreateAIConfig_FullMethodName = "/autoforward.AIControlService/CreateAIConfig"
	AIControlService_UpdateAIConfig_FullMethodName = "/autoforward.AIControlService/UpdateAIConfig"
	AIControlService_DeleteAIConfig_FullMethodName = "/autoforward.AIControlService/DeleteAIConfig"
	AIControlService_TestAIRewrite_FullMethodName  = "/autoforward.AIControlService/TestAIRewrite"
)

// AIControlServiceClient is the client API for AIControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIControlServiceClient interface {
	ListAIConfigs(ctx context.Context, in *ListAIConfigsRequest, opts ...grpc.CallOption) (*ListAIConfigsResponse, error)
	CreateAIConfig(ctx context.Context, in *CreateAIConfigRequest, opts ...grpc.CallOption) (*AIConfig, error)
	UpdateAIConfig(ctx context.Context, in *UpdateAIConfigRequest, opts ...grpc.CallOption) (*AIConfig, error)
	DeleteAIConfig(ctx context.Context, in *DeleteAIConfigRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	TestAIRewrite(ctx context.Context, in *TestAIRewriteRequest, opts ...grpc.CallOption) (*TestAIRewriteResponse, error)
}

type aIControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIControlServiceClient(cc grpc.ClientConnInterface) AIControlServiceClient {
	return &aIControlServiceClient{cc}
}

func (c *aIControlServiceClient) ListAIConfigs(ctx context.Context, in *ListAIConfigsRequest, opts ...grpc.CallOption) (*ListAIConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAIConfigsResponse)
	err := c.cc.Invoke(ctx, AIControlService_ListAIConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIControlServiceClient) CreateAIConfig(ctx context.Context, in *CreateAIConfigRequest, opts ...grpc.CallOption) (*AIConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIConfig)
	err := c.cc.Invoke(ctx, AIControlService_CreateAIConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIControlServiceClient) UpdateAIConfig(ctx context.Context, in *UpdateAIConfigRequest, opts ...grpc.CallOption) (*AIConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIConfig)
	err := c.cc.Invoke(ctx, AIControlService_UpdateAIConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIControlServiceClient) DeleteAIConfig(ctx context.Context, in *DeleteAIConfigRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AIControlService_DeleteAIConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIControlServiceClient) TestAIRewrite(ctx context.Context, in *TestAIRewriteRequest, opts ...grpc.CallOption) (*TestAIRewriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestAIRewriteResponse)
	err := c.cc.Invoke(ctx, AIControlService_TestAIRewrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIControlServiceServer is the server API for AIControlService service.
// All implementations must embed UnimplementedAIControlServiceServer
// for forward compatibility
type AIControlServiceServer interface {
	ListAIConfigs(context.Context, *ListAIConfigsRequest) (*ListAIConfigsResponse, error)
	CreateAIConfig(context.Context, *CreateAIConfigRequest) (*AIConfig, error)
	UpdateAIConfig(context.Context, *UpdateAIConfigRequest) (*AIConfig, error)
	DeleteAIConfig(context.Context, *DeleteAIConfigRequest) (*StatusResponse, error)
	TestAIRewrite(context.Context, *TestAIRewriteRequest) (*TestAIRewriteResponse, error)
	mustEmbedUnimplementedAIControlServiceServer()
}

// UnimplementedAIControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIControlServiceServer struct {
}

func (UnimplementedAIControlServiceServer) ListAIConfigs(context.Context, *ListAIConfigsRequest) (*ListAIConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAIConfigs not implemented")
}
func (UnimplementedAIControlServiceServer) CreateAIConfig(context.Context, *CreateAIConfigRequest) (*AIConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAIConfig not implemented")
}
func (UnimplementedAIControlServiceServer) UpdateAIConfig(context.Context, *UpdateAIConfigRequest) (*AIConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAIConfig not implemented")
}
func (UnimplementedAIControlServiceServer) DeleteAIConfig(context.Context, *DeleteAIConfigRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAIConfig not implemented")
}
func (UnimplementedAIControlServiceServer) TestAIRewrite(context.Context, *TestAIRewriteRequest) (*TestAIRewriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestAIRewrite not implemented")
}
func (UnimplementedAIControlServiceServer) mustEmbedUnimplementedAIControlServiceServer() {}

// UnsafeAIControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIControlServiceServer will
// result in compilation errors.
type UnsafeAIControlServiceServer interface {
	mustEmbedUnimplementedAIControlServiceServer()
}

func RegisterAIControlServiceServer(s grpc.ServiceRegistrar, srv AIControlServiceServer) {
	s.RegisterService(&AIControlService_ServiceDesc, srv)
}

func _AIControlService_ListAIConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAIConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIControlServiceServer).ListAIConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIControlService_ListAIConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIControlServiceServer).ListAIConfigs(ctx, req.(*ListAIConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIControlService_CreateAIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIControlServiceServer).CreateAIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIControlService_CreateAIConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIControlServiceServer).CreateAIConfig(ctx, req.(*CreateAIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIControlService_UpdateAIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIControlServiceServer).UpdateAIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIControlService_UpdateAIConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIControlServiceServer).UpdateAIConfig(ctx, req.(*UpdateAIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIControlService_DeleteAIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIControlServiceServer).DeleteAIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIControlService_DeleteAIConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIControlServiceServer).DeleteAIConfig(ctx, req.(*DeleteAIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIControlService_TestAIRewrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestAIRewriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIControlServiceServer).TestAIRewrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIControlService_TestAIRewrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIControlServiceServer).TestAIRewrite(ctx, req.(*TestAIRewriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIControlService_ServiceDesc is the grpc.ServiceDesc for AIControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.AIControlService",
	HandlerType: (*AIControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAIConfigs",
			Handler:    _AIControlService_ListAIConfigs_Handler,
		},
		{
			MethodName: "CreateAIConfig",
			Handler:    _AIControlService_CreateAIConfig_Handler,
		},
		{
			MethodName: "UpdateAIConfig",
			Handler:    _AIControlService_UpdateAIConfig_Handler,
		},
		{
			MethodName: "DeleteAIConfig",
			Handler:    _AIControlService_DeleteAIConfig_Handler,
		},
		{
			MethodName: "TestAIRewrite",
			Handler:    _AIControlService_TestAIRewrite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}

const (
	SystemStatusControlService_GetSystemStats_FullMethodName = "/autoforward.SystemStatusControlService/GetSystemStats"
)

// SystemStatusControlServiceClient is the client API for SystemStatusControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemStatusControlServiceClient interface {
	GetSystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (*SystemStatsResponse, error)
}

type systemStatusControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemStatusControlServiceClient(cc grpc.ClientConnInterface) SystemStatusControlServiceClient {
	return &systemStatusControlServiceClient{cc}
}

func (c *systemStatusControlServiceClient) GetSystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (*SystemStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStatsResponse)
	err := c.cc.Invoke(ctx, SystemStatusControlService_GetSystemStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemStatusControlServiceServer is the server API for SystemStatusControlService service.
// All implementations must embed UnimplementedSystemStatusControlServiceServer
// for forward compatibility
type SystemStatusControlServiceServer interface {
	GetSystemStats(context.Context, *SystemStatsRequest) (*SystemStatsResponse, error)
	mustEmbedUnimplementedSystemStatusControlServiceServer()
}

// UnimplementedSystemStatusControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSystemStatusControlServiceServer struct {
}

func (UnimplementedSystemStatusControlServiceServer) GetSystemStats(context.Context, *SystemStatsRequest) (*SystemStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemStats not implemented")
}
func (UnimplementedSystemStatusControlServiceServer) mustEmbedUnimplementedSystemStatusControlServiceServer() {
}

// UnsafeSystemStatusControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemStatusControlServiceServer will
// result in compilation errors.
type UnsafeSystemStatusControlServiceServer interface {
	mustEmbedUnimplementedSystemStatusControlServiceServer()
}

func RegisterSystemStatusControlServiceServer(s grpc.ServiceRegistrar, srv SystemStatusControlServiceServer) {
	s.RegisterService(&SystemStatusControlService_ServiceDesc, srv)
}

func _SystemStatusControlService_GetSystemStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemStatusControlServiceServer).GetSystemStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemStatusControlService_GetSystemStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemStatusControlServiceServer).GetSystemStats(ctx, req.(*SystemStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemStatusControlService_ServiceDesc is the grpc.ServiceDesc for SystemStatusControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemStatusControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.SystemStatusControlService",
	HandlerType: (*SystemStatusControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemStats",
			Handler:    _SystemStatusControlService_GetSystemStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}

const (
	LogControlService_Log_FullMethodName       = "/autoforward.LogControlService/Log"
	LogControlService_QueryLogs_FullMethodName = "/autoforward.LogControlService/QueryLogs"
	LogControlService_LogStats_FullMethodName  = "/autoforward.LogControlService/LogStats"
)

// LogControlServiceClient is the client API for LogControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogControlServiceClient interface {
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	QueryLogs(ctx context.Context, in *QueryLogsRequest, opts ...grpc.CallOption) (*QueryLogsResponse, error)
	LogStats(ctx context.Context, in *LogStatsRequest, opts ...grpc.CallOption) (*LogStatsResponse, error)
}

type logControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogControlServiceClient(cc grpc.ClientConnInterface) LogControlServiceClient {
	return &logControlServiceClient{cc}
}

func (c *logControlServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, LogControlService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logControlServiceClient) QueryLogs(ctx context.Context, in *QueryLogsRequest, opts ...grpc.CallOption) (*QueryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLogsResponse)
	err := c.cc.Invoke(ctx, LogControlService_QueryLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logControlServiceClient) LogStats(ctx context.Context, in *LogStatsRequest, opts ...grpc.CallOption) (*LogStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogStatsResponse)
	err := c.cc.Invoke(ctx, LogControlService_LogStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogControlServiceServer is the server API for LogControlService service.
// All implementations must embed UnimplementedLogControlServiceServer
// for forward compatibility
type LogControlServiceServer interface {
	Log(context.Context, *LogRequest) (*StatusResponse, error)
	QueryLogs(context.Context, *QueryLogsRequest) (*QueryLogsResponse, error)
	LogStats(context.Context, *LogStatsRequest) (*LogStatsResponse, error)
	mustEmbedUnimplementedLogControlServiceServer()
}

// UnimplementedLogControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogControlServiceServer struct {
}

func (UnimplementedLogControlServiceServer) Log(context.Context, *LogRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedLogControlServiceServer) QueryLogs(context.Context, *QueryLogsRequest) (*QueryLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLogs not implemented")
}
func (UnimplementedLogControlServiceServer) LogStats(context.Context, *LogStatsRequest) (*LogStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogStats not implemented")
}
func (UnimplementedLogControlServiceServer) mustEmbedUnimplementedLogControlServiceServer() {}

// UnsafeLogControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogControlServiceServer will
// result in compilation errors.
type UnsafeLogControlServiceServer interface {
	mustEmbedUnimplementedLogControlServiceServer()
}

func RegisterLogControlServiceServer(s grpc.ServiceRegistrar, srv LogControlServiceServer) {
	s.RegisterService(&LogControlService_ServiceDesc, srv)
}

func _LogControlService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogControlServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogControlService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogControlServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogControlService_QueryLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogControlServiceServer).QueryLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogControlService_QueryLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogControlServiceServer).QueryLogs(ctx, req.(*QueryLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogControlService_LogStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogControlServiceServer).LogStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogControlService_LogStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogControlServiceServer).LogStats(ctx, req.(*LogStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogControlService_ServiceDesc is the grpc.ServiceDesc for LogControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.LogControlService",
	HandlerType: (*LogControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _LogControlService_Log_Handler,
		},
		{
			MethodName: "QueryLogs",
			Handler:    _LogControlService_QueryLogs_Handler,
		},
		{
			MethodName: "LogStats",
			Handler:    _LogControlService_LogStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}

const (
	AccountControlService_RegisterAccount_FullMethodName = "/autoforward.AccountControlService/RegisterAccount"
	AccountControlService_LoginAccount_FullMethodName    = "/autoforward.AccountControlService/LoginAccount"
	AccountControlService_ValidateToken_FullMethodName   = "/autoforward.AccountControlService/ValidateToken"
	AccountControlService_IssueWebToken_FullMethodName   = "/autoforward.AccountControlService/IssueWebToken"
	AccountControlService_ChangePassword_FullMethodName  = "/autoforward.AccountControlService/ChangePassword"
	AccountControlService_GetAccount_FullMethodName      = "/autoforward.AccountControlService/GetAccount"
)

// AccountControlServiceClient is the client API for AccountControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountControlServiceClient interface {
	RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error)
	LoginAccount(ctx context.Context, in *LoginAccountRequest, opts ...grpc.CallOption) (*LoginAccountResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	IssueWebToken(ctx context.Context, in *IssueWebTokenRequest, opts ...grpc.CallOption) (*LoginAccountResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*WebAccount, error)
}

type accountControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountControlServiceClient(cc grpc.ClientConnInterface) AccountControlServiceClient {
	return &accountControlServiceClient{cc}
}

func (c *accountControlServiceClient) RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAccountResponse)
	err := c.cc.Invoke(ctx, AccountControlService_RegisterAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountControlServiceClient) LoginAccount(ctx context.Context, in *LoginAccountRequest, opts ...grpc.CallOption) (*LoginAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginAccountResponse)
	err := c.cc.Invoke(ctx, AccountControlService_LoginAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountControlServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, AccountControlService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountControlServiceClient) IssueWebToken(ctx context.Context, in *IssueWebTokenRequest, opts ...grpc.CallOption) (*LoginAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginAccountResponse)
	err := c.cc.Invoke(ctx, AccountControlService_IssueWebToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountControlServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AccountControlService_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountControlServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*WebAccount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebAccount)
	err := c.cc.Invoke(ctx, AccountControlService_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountControlServiceServer is the server API for AccountControlService service.
// All implementations must embed UnimplementedAccountControlServiceServer
// for forward compatibility
type AccountControlServiceServer interface {
	RegisterAccount(context.Context, *RegisterAccountRequest) (*RegisterAccountResponse, error)
	LoginAccount(context.Context, *LoginAccountRequest) (*LoginAccountResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	IssueWebToken(context.Context, *IssueWebTokenRequest) (*LoginAccountResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*StatusResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*WebAccount, error)
	mustEmbedUnimplementedAccountControlServiceServer()
}

// UnimplementedAccountControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountControlServiceServer struct {
}

func (UnimplementedAccountControlServiceServer) RegisterAccount(context.Context, *RegisterAccountRequest) (*RegisterAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAccount not implemented")
}
func (UnimplementedAccountControlServiceServer) LoginAccount(context.Context, *LoginAccountRequest) (*LoginAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAccount not implemented")
}
func (UnimplementedAccountControlServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAccountControlServiceServer) IssueWebToken(context.Context, *IssueWebTokenRequest) (*LoginAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueWebToken not implemented")
}
func (UnimplementedAccountControlServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedAccountControlServiceServer) GetAccount(context.Context, *GetAccountRequest) (*WebAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedAccountControlServiceServer) mustEmbedUnimplementedAccountControlServiceServer() {}

// UnsafeAccountControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountControlServiceServer will
// result in compilation errors.
type UnsafeAccountControlServiceServer interface {
	mustEmbedUnimplementedAccountControlServiceServer()
}

func RegisterAccountControlServiceServer(s grpc.ServiceRegistrar, srv AccountControlServiceServer) {
	s.RegisterService(&AccountControlService_ServiceDesc, srv)
}

func _AccountControlService_RegisterAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountControlServiceServer).RegisterAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountControlService_RegisterAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountControlServiceServer).RegisterAccount(ctx, req.(*RegisterAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountControlService_LoginAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountControlServiceServer).LoginAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountControlService_LoginAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountControlServiceServer).LoginAccount(ctx, req.(*LoginAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountControlService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountControlServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountControlService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountControlServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountControlService_IssueWebToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueWebTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountControlServiceServer).IssueWebToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountControlService_IssueWebToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountControlServiceServer).IssueWebToken(ctx, req.(*IssueWebTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountControlService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountControlServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountControlService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountControlServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountControlService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountControlServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountControlService_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountControlServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountControlService_ServiceDesc is the grpc.ServiceDesc for AccountControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.AccountControlService",
	HandlerType: (*AccountControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAccount",
			Handler:    _AccountControlService_RegisterAccount_Handler,
		},
		{
			MethodName: "LoginAccount",
			Handler:    _AccountControlService_LoginAccount_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _AccountControlService_ValidateToken_Handler,
		},
		{
			MethodName: "IssueWebToken",
			Handler:    _AccountControlService_IssueWebToken_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _AccountControlService_ChangePassword_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _AccountControlService_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}
