// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: autoforward.proto

package autoforwardpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionControlService_ListSessions_FullMethodName     = "/autoforward.SessionControlService/ListSessions"
	SessionControlService_StartLogin_FullMethodName       = "/autoforward.SessionControlService/StartLogin"
	SessionControlService_SubmitCode_FullMethodName       = "/autoforward.SessionControlService/SubmitCode"
	SessionControlService_SubmitPassword_FullMethodName   = "/autoforward.SessionControlService/SubmitPassword"
	SessionControlService_BackupSession_FullMethodName    = "/autoforward.SessionControlService/BackupSession"
	SessionControlService_RestoreSession_FullMethodName   = "/autoforward.SessionControlService/RestoreSession"
	SessionControlService_TerminateSession_FullMethodName = "/autoforward.SessionControlService/TerminateSession"
)

// SessionControlServiceClient is the client API for SessionControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionControlServiceClient interface {
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error)
	SubmitCode(ctx context.Context, in *SubmitCodeRequest, opts ...grpc.CallOption) (*SubmitCodeResponse, error)
	SubmitPassword(ctx context.Context, in *SubmitPasswordRequest, opts ...grpc.CallOption) (*SubmitPasswordResponse, error)
	BackupSession(ctx context.Context, in *BackupSessionRequest, opts ...grpc.CallOption) (*BackupSessionResponse, error)
	RestoreSession(ctx context.Context, in *RestoreSessionRequest, opts ...grpc.CallOption) (*RestoreSessionResponse, error)
	TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type sessionControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionControlServiceClient(cc grpc.ClientConnInterface) SessionControlServiceClient {
	return &sessionControlServiceClient{cc}
}

func (c *sessionControlServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, SessionControlService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLoginResponse)
	err := c.cc.Invoke(ctx, SessionControlService_StartLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) SubmitCode(ctx context.Context, in *SubmitCodeRequest, opts ...grpc.CallOption) (*SubmitCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCodeResponse)
	err := c.cc.Invoke(ctx, SessionControlService_SubmitCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) SubmitPassword(ctx context.Context, in *SubmitPasswordRequest, opts ...grpc.CallOption) (*SubmitPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitPasswordResponse)
	err := c.cc.Invoke(ctx, SessionControlService_SubmitPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) BackupSession(ctx context.Context, in *BackupSessionRequest, opts ...grpc.CallOption) (*BackupSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupSessionResponse)
	err := c.cc.Invoke(ctx, SessionControlService_BackupSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) RestoreSession(ctx context.Context, in *RestoreSessionRequest, opts ...grpc.CallOption) (*RestoreSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreSessionResponse)
	err := c.cc.Invoke(ctx, SessionControlService_RestoreSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionControlServiceClient) TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, SessionControlService_TerminateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionControlServiceServer is the server API for SessionControlService service.
// All implementations must embed UnimplementedSessionControlServiceServer
// for forward compatibility.
type SessionControlServiceServer interface {
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error)
	SubmitCode(context.Context, *SubmitCodeRequest) (*SubmitCodeResponse, error)
	SubmitPassword(context.Context, *SubmitPasswordRequest) (*SubmitPasswordResponse, error)
	BackupSession(context.Context, *BackupSessionRequest) (*BackupSessionResponse, error)
	RestoreSession(context.Context, *RestoreSessionRequest) (*RestoreSessionResponse, error)
	TerminateSession(context.Context, *TerminateSessionRequest) (*StatusResponse, error)
	mustEmbedUnimplementedSessionControlServiceServer()
}

// UnimplementedSessionControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionControlServiceServer struct{}

func (UnimplementedSessionControlServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSessionControlServiceServer) StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartLogin not implemented")
}
func (UnimplementedSessionControlServiceServer) SubmitCode(context.Context, *SubmitCodeRequest) (*SubmitCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCode not implemented")
}
func (UnimplementedSessionControlServiceServer) SubmitPassword(context.Context, *SubmitPasswordRequest) (*SubmitPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitPassword not implemented")
}
func (UnimplementedSessionControlServiceServer) BackupSession(context.Context, *BackupSessionRequest) (*BackupSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BackupSession not implemented")
}
func (UnimplementedSessionControlServiceServer) RestoreSession(context.Context, *RestoreSessionRequest) (*RestoreSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreSession not implemented")
}
func (UnimplementedSessionControlServiceServer) TerminateSession(context.Context, *TerminateSessionRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateSession not implemented")
}
func (UnimplementedSessionControlServiceServer) mustEmbedUnimplementedSessionControlServiceServer() {}
func (UnimplementedSessionControlServiceServer) testEmbeddedByValue()                               {}

// UnsafeSessionControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionControlServiceServer will
// result in compilation errors.
type UnsafeSessionControlServiceServer interface {
	mustEmbedUnimplementedSessionControlServiceServer()
}

func RegisterSessionControlServiceServer(s grpc.ServiceRegistrar, srv SessionControlServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionControlService_ServiceDesc, srv)
}

func _SessionControlService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_StartLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).StartLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_StartLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).StartLogin(ctx, req.(*StartLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_SubmitCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).SubmitCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_SubmitCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).SubmitCode(ctx, req.(*SubmitCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_SubmitPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).SubmitPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_SubmitPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).SubmitPassword(ctx, req.(*SubmitPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_BackupSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).BackupSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_BackupSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).BackupSession(ctx, req.(*BackupSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_RestoreSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).RestoreSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_RestoreSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).RestoreSession(ctx, req.(*RestoreSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionControlService_TerminateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionControlServiceServer).TerminateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionControlService_TerminateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionControlServiceServer).TerminateSession(ctx, req.(*TerminateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionControlService_ServiceDesc is the grpc.ServiceDesc for SessionControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.SessionControlService",
	HandlerType: (*SessionControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSessions",
			Handler:    _SessionControlService_ListSessions_Handler,
		},
		{
			MethodName: "StartLogin",
			Handler:    _SessionControlService_StartLogin_Handler,
		},
		{
			MethodName: "SubmitCode",
			Handler:    _SessionControlService_SubmitCode_Handler,
		},
		{
			MethodName: "SubmitPassword",
			Handler:    _SessionControlService_SubmitPassword_Handler,
		},
		{
			MethodName: "BackupSession",
			Handler:    _SessionControlService_BackupSession_Handler,
		},
		{
			MethodName: "RestoreSession",
			Handler:    _SessionControlService_RestoreSession_Handler,
		},
		{
			MethodName: "TerminateSession",
			Handler:    _SessionControlService_TerminateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}

const (
	ForwardRuleControlService_ListRules_FullMethodName  = "/autoforward.ForwardRuleControlService/ListRules"
	ForwardRuleControlService_CreateRule_FullMethodName = "/autoforward.ForwardRuleControlService/CreateRule"
	ForwardRuleControlService_UpdateRule_FullMethodName = "/autoforward.ForwardRuleControlService/UpdateRule"
	ForwardRuleControlService_DeleteRule_FullMethodName = "/autoforward.ForwardRuleControlService/DeleteRule"
)

// ForwardRuleControlServiceClient is the client API for ForwardRuleControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForwardRuleControlServiceClient interface {
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*ForwardRule, error)
	UpdateRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*ForwardRule, error)
	DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type forwardRuleControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardRuleControlServiceClient(cc grpc.ClientConnInterface) ForwardRuleControlServiceClient {
	return &forwardRuleControlServiceClient{cc}
}

func (c *forwardRuleControlServiceClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, ForwardRuleControlService_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardRuleControlServiceClient) CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*ForwardRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardRule)
	err := c.cc.Invoke(ctx, ForwardRuleControlService_CreateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardRuleControlServiceClient) UpdateRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*ForwardRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardRule)
	err := c.cc.Invoke(ctx, ForwardRuleControlService_UpdateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardRuleControlServiceClient) DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ForwardRuleControlService_DeleteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardRuleControlServiceServer is the server API for ForwardRuleControlService service.
// All implementations must embed UnimplementedForwardRuleControlServiceServer
// for forward compatibility.
type ForwardRuleControlServiceServer interface {
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	CreateRule(context.Context, *CreateRuleRequest) (*ForwardRule, error)
	UpdateRule(context.Context, *UpdateRuleRequest) (*ForwardRule, error)
	DeleteRule(context.Context, *DeleteRuleRequest) (*StatusResponse, error)
	mustEmbedUnimplementedForwardRuleControlServiceServer()
}

// UnimplementedForwardRuleControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForwardRuleControlServiceServer struct{}

func (UnimplementedForwardRuleControlServiceServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedForwardRuleControlServiceServer) CreateRule(context.Context, *CreateRuleRequest) (*ForwardRule, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRule not implemented")
}
func (UnimplementedForwardRuleControlServiceServer) UpdateRule(context.Context, *UpdateRuleRequest) (*ForwardRule, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRule not implemented")
}
func (UnimplementedForwardRuleControlServiceServer) DeleteRule(context.Context, *DeleteRuleRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRule not implemented")
}
func (UnimplementedForwardRuleControlServiceServer) mustEmbedUnimplementedForwardRuleControlServiceServer() {
}
func (UnimplementedForwardRuleControlServiceServer) testEmbeddedByValue() {}

// UnsafeForwardRuleControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwardRuleControlServiceServer will
// result in compilation errors.
type UnsafeForwardRuleControlServiceServer interface {
	mustEmbedUnimplementedForwardRuleControlServiceServer()
}

func RegisterForwardRuleControlServiceServer(s grpc.ServiceRegistrar, srv ForwardRuleControlServiceServer) {
	// If the following call panics, it indicates UnimplementedForwardRuleControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForwardRuleControlService_ServiceDesc, srv)
}

func _ForwardRuleControlService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardRuleControlServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardRuleControlService_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardRuleControlServiceServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardRuleControlService_CreateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardRuleControlServiceServer).CreateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardRuleControlService_CreateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardRuleControlServiceServer).CreateRule(ctx, req.(*CreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardRuleControlService_UpdateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardRuleControlServiceServer).UpdateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardRuleControlService_UpdateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardRuleControlServiceServer).UpdateRule(ctx, req.(*UpdateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardRuleControlService_DeleteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardRuleControlServiceServer).DeleteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardRuleControlService_DeleteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardRuleControlServiceServer).DeleteRule(ctx, req.(*DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForwardRuleControlService_ServiceDesc is the grpc.ServiceDesc for ForwardRuleControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwardRuleControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.ForwardRuleControlService",
	HandlerType: (*ForwardRuleControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRules",
			Handler:    _ForwardRuleControlService_ListRules_Handler,
		},
		{
			MethodName: "CreateRule",
			Handler:    _ForwardRuleControlService_CreateRule_Handler,
		},
		{
			MethodName: "UpdateRule",
			Handler:    _ForwardRuleControlService_UpdateRule_Handler,
		},
		{
			MethodName: "DeleteRule",
			Handler:    _ForwardRuleControlService_DeleteRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}

const (
	FilterControlService_ListFilters_FullMethodName  = "/autoforward.FilterControlService/ListFilters"
	FilterControlService_CreateFilter_FullMethodName = "/autoforward.FilterControlService/CreateFilter"
	FilterControlService_UpdateFilter_FullMethodName = "/autoforward.FilterControlService/UpdateFilter"
	FilterControlService_DeleteFilter_FullMethodName = "/autoforward.FilterControlService/DeleteFilter"
)

// FilterControlServiceClient is the client API for FilterControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilterControlServiceClient interface {
	ListFilters(ctx context.Context, in *ListFiltersRequest, opts ...grpc.CallOption) (*ListFiltersResponse, error)
	CreateFilter(ctx context.Context, in *CreateFilterRequest, opts ...grpc.CallOption) (*FilterRule, error)
	UpdateFilter(ctx context.Context, in *UpdateFilterRequest, opts ...grpc.CallOption) (*FilterRule, error)
	DeleteFilter(ctx context.Context, in *DeleteFilterRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type filterControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilterControlServiceClient(cc grpc.ClientConnInterface) FilterControlServiceClient {
	return &filterControlServiceClient{cc}
}

func (c *filterControlServiceClient) ListFilters(ctx context.Context, in *ListFiltersRequest, opts ...grpc.CallOption) (*ListFiltersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFiltersResponse)
	err := c.cc.Invoke(ctx, FilterControlService_ListFilters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filterControlServiceClient) CreateFilter(ctx context.Context, in *CreateFilterRequest, opts ...grpc.CallOption) (*FilterRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterRule)
	err := c.cc.Invoke(ctx, FilterControlService_CreateFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filterControlServiceClient) UpdateFilter(ctx context.Context, in *UpdateFilterRequest, opts ...grpc.CallOption) (*FilterRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterRule)
	err := c.cc.Invoke(ctx, FilterControlService_UpdateFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filterControlServiceClient) DeleteFilter(ctx context.Context, in *DeleteFilterRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, FilterControlService_DeleteFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilterControlServiceServer is the server API for FilterControlService service.
// All implementations must embed UnimplementedFilterControlServiceServer
// for forward compatibility.
type FilterControlServiceServer interface {
	ListFilters(context.Context, *ListFiltersRequest) (*ListFiltersResponse, error)
	CreateFilter(context.Context, *CreateFilterRequest) (*FilterRule, error)
	UpdateFilter(context.Context, *UpdateFilterRequest) (*FilterRule, error)
	DeleteFilter(context.Context, *DeleteFilterRequest) (*StatusResponse, error)
	mustEmbedUnimplementedFilterControlServiceServer()
}

// UnimplementedFilterControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilterControlServiceServer struct{}

func (UnimplementedFilterControlServiceServer) ListFilters(context.Context, *ListFiltersRequest) (*ListFiltersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFilters not implemented")
}
func (UnimplementedFilterControlServiceServer) CreateFilter(context.Context, *CreateFilterRequest) (*FilterRule, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFilter not implemented")
}
func (UnimplementedFilterControlServiceServer) UpdateFilter(context.Context, *UpdateFilterRequest) (*FilterRule, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFilter not implemented")
}
func (UnimplementedFilterControlServiceServer) DeleteFilter(context.Context, *DeleteFilterRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFilter not implemented")
}
func (UnimplementedFilterControlServiceServer) mustEmbedUnimplementedFilterControlServiceServer() {}
func (UnimplementedFilterControlServiceServer) testEmbeddedByValue()                              {}

// UnsafeFilterControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilterControlServiceServer will
// result in compilation errors.
type UnsafeFilterControlServiceServer interface {
	mustEmbedUnimplementedFilterControlServiceServer()
}

func RegisterFilterControlServiceServer(s grpc.ServiceRegistrar, srv FilterControlServiceServer) {
	// If the following call panics, it indicates UnimplementedFilterControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FilterControlService_ServiceDesc, srv)
}

func _FilterControlService_ListFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFiltersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterControlServiceServer).ListFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterControlService_ListFilters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterControlServiceServer).ListFilters(ctx, req.(*ListFiltersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilterControlService_CreateFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterControlServiceServer).CreateFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterControlService_CreateFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterControlServiceServer).CreateFilter(ctx, req.(*CreateFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilterControlService_UpdateFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterControlServiceServer).UpdateFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterControlService_UpdateFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterControlServiceServer).UpdateFilter(ctx, req.(*UpdateFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilterControlService_DeleteFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterControlServiceServer).DeleteFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterControlService_DeleteFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterControlServiceServer).DeleteFilter(ctx, req.(*DeleteFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilterControlService_ServiceDesc is the grpc.ServiceDesc for FilterControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilterControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.FilterControlService",
	HandlerType: (*FilterControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFilters",
			Handler:    _FilterControlService_ListFilters_Handler,
		},
		{
			MethodName: "CreateFilter",
			Handler:    _FilterControlService_CreateFilter_Handler,
		},
		{
			MethodName: "UpdateFilter",
			Handler:    _FilterControlService_UpdateFilter_Handler,
		},
		{
			MethodName: "DeleteFilter",
			Handler:    _FilterControlService_DeleteFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}

const (
	AIControlService_ListAIConfigs_FullMethodName  = "/autoforward.AIControlService/ListAIConfigs"
	AIControlService_CreateAIConfig_FullMethodName = "/autoforward.AIControlService/CreateAIConfig"
	AIControlService_UpdateAIConfig_FullMethodName = "/autoforward.AIControlService/UpdateAIConfig"
	AIControlService_DeleteAIConfig_FullMethodName = "/autoforward.AIControlService/DeleteAIConfig"
	AIControlService_TestAIRewrite_FullMethodName  = "/autoforward.AIControlService/TestAIRewrite"
)

// AIControlServiceClient is the client API for AIControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIControlServiceClient interface {
	ListAIConfigs(ctx context.Context, in *ListAIConfigsRequest, opts ...grpc.CallOption) (*ListAIConfigsResponse, error)
	CreateAIConfig(ctx context.Context, in *CreateAIConfigRequest, opts ...grpc.CallOption) (*AIConfig, error)
	UpdateAIConfig(ctx context.Context, in *UpdateAIConfigRequest, opts ...grpc.CallOption) (*AIConfig, error)
	DeleteAIConfig(ctx context.Context, in *DeleteAIConfigRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	TestAIRewrite(ctx context.Context, in *TestAIRewriteRequest, opts ...grpc.CallOption) (*TestAIRewriteResponse, error)
}

type aIControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIControlServiceClient(cc grpc.ClientConnInterface) AIControlServiceClient {
	return &aIControlServiceClient{cc}
}

func (c *aIControlServiceClient) ListAIConfigs(ctx context.Context, in *ListAIConfigsRequest, opts ...grpc.CallOption) (*ListAIConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAIConfigsResponse)
	err := c.cc.Invoke(ctx, AIControlService_ListAIConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIControlServiceClient) CreateAIConfig(ctx context.Context, in *CreateAIConfigRequest, opts ...grpc.CallOption) (*AIConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIConfig)
	err := c.cc.Invoke(ctx, AIControlService_CreateAIConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIControlServiceClient) UpdateAIConfig(ctx context.Context, in *UpdateAIConfigRequest, opts ...grpc.CallOption) (*AIConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIConfig)
	err := c.cc.Invoke(ctx, AIControlService_UpdateAIConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIControlServiceClient) DeleteAIConfig(ctx context.Context, in *DeleteAIConfigRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AIControlService_DeleteAIConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIControlServiceClient) TestAIRewrite(ctx context.Context, in *TestAIRewriteRequest, opts ...grpc.CallOption) (*TestAIRewriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestAIRewriteResponse)
	err := c.cc.Invoke(ctx, AIControlService_TestAIRewrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIControlServiceServer is the server API for AIControlService service.
// All implementations must embed UnimplementedAIControlServiceServer
// for forward compatibility.
type AIControlServiceServer interface {
	ListAIConfigs(context.Context, *ListAIConfigsRequest) (*ListAIConfigsResponse, error)
	CreateAIConfig(context.Context, *CreateAIConfigRequest) (*AIConfig, error)
	UpdateAIConfig(context.Context, *UpdateAIConfigRequest) (*AIConfig, error)
	DeleteAIConfig(context.Context, *DeleteAIConfigRequest) (*StatusResponse, error)
	TestAIRewrite(context.Context, *TestAIRewriteRequest) (*TestAIRewriteResponse, error)
	mustEmbedUnimplementedAIControlServiceServer()
}

// UnimplementedAIControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIControlServiceServer struct{}

func (UnimplementedAIControlServiceServer) ListAIConfigs(context.Context, *ListAIConfigsRequest) (*ListAIConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAIConfigs not implemented")
}
func (UnimplementedAIControlServiceServer) CreateAIConfig(context.Context, *CreateAIConfigRequest) (*AIConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAIConfig not implemented")
}
func (UnimplementedAIControlServiceServer) UpdateAIConfig(context.Context, *UpdateAIConfigRequest) (*AIConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAIConfig not implemented")
}
func (UnimplementedAIControlServiceServer) DeleteAIConfig(context.Context, *DeleteAIConfigRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAIConfig not implemented")
}
func (UnimplementedAIControlServiceServer) TestAIRewrite(context.Context, *TestAIRewriteRequest) (*TestAIRewriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestAIRewrite not implemented")
}
func (UnimplementedAIControlServiceServer) mustEmbedUnimplementedAIControlServiceServer() {}
func (UnimplementedAIControlServiceServer) testEmbeddedByValue()                          {}

// UnsafeAIControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIControlServiceServer will
// result in compilation errors.
type UnsafeAIControlServiceServer interface {
	mustEmbedUnimplementedAIControlServiceServer()
}

func RegisterAIControlServiceServer(s grpc.ServiceRegistrar, srv AIControlServiceServer) {
	// If the following call panics, it indicates UnimplementedAIControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIControlService_ServiceDesc, srv)
}

func _AIControlService_ListAIConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAIConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIControlServiceServer).ListAIConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIControlService_ListAIConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIControlServiceServer).ListAIConfigs(ctx, req.(*ListAIConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIControlService_CreateAIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIControlServiceServer).CreateAIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIControlService_CreateAIConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIControlServiceServer).CreateAIConfig(ctx, req.(*CreateAIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIControlService_UpdateAIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIControlServiceServer).UpdateAIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIControlService_UpdateAIConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIControlServiceServer).UpdateAIConfig(ctx, req.(*UpdateAIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIControlService_DeleteAIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIControlServiceServer).DeleteAIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIControlService_DeleteAIConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIControlServiceServer).DeleteAIConfig(ctx, req.(*DeleteAIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIControlService_TestAIRewrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestAIRewriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIControlServiceServer).TestAIRewrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIControlService_TestAIRewrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIControlServiceServer).TestAIRewrite(ctx, req.(*TestAIRewriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIControlService_ServiceDesc is the grpc.ServiceDesc for AIControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.AIControlService",
	HandlerType: (*AIControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAIConfigs",
			Handler:    _AIControlService_ListAIConfigs_Handler,
		},
		{
			MethodName: "CreateAIConfig",
			Handler:    _AIControlService_CreateAIConfig_Handler,
		},
		{
			MethodName: "UpdateAIConfig",
			Handler:    _AIControlService_UpdateAIConfig_Handler,
		},
		{
			MethodName: "DeleteAIConfig",
			Handler:    _AIControlService_DeleteAIConfig_Handler,
		},
		{
			MethodName: "TestAIRewrite",
			Handler:    _AIControlService_TestAIRewrite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}

const (
	SystemStatusControlService_GetSystemStats_FullMethodName = "/autoforward.SystemStatusControlService/GetSystemStats"
)

// SystemStatusControlServiceClient is the client API for SystemStatusControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemStatusControlServiceClient interface {
	GetSystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (*SystemStatsResponse, error)
}

type systemStatusControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemStatusControlServiceClient(cc grpc.ClientConnInterface) SystemStatusControlServiceClient {
	return &systemStatusControlServiceClient{cc}
}

func (c *systemStatusControlServiceClient) GetSystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (*SystemStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStatsResponse)
	err := c.cc.Invoke(ctx, SystemStatusControlService_GetSystemStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemStatusControlServiceServer is the server API for SystemStatusControlService service.
// All implementations must embed UnimplementedSystemStatusControlServiceServer
// for forward compatibility.
type SystemStatusControlServiceServer interface {
	GetSystemStats(context.Context, *SystemStatsRequest) (*SystemStatsResponse, error)
	mustEmbedUnimplementedSystemStatusControlServiceServer()
}

// UnimplementedSystemStatusControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemStatusControlServiceServer struct{}

func (UnimplementedSystemStatusControlServiceServer) GetSystemStats(context.Context, *SystemStatsRequest) (*SystemStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemStats not implemented")
}
func (UnimplementedSystemStatusControlServiceServer) mustEmbedUnimplementedSystemStatusControlServiceServer() {
}
func (UnimplementedSystemStatusControlServiceServer) testEmbeddedByValue() {}

// UnsafeSystemStatusControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemStatusControlServiceServer will
// result in compilation errors.
type UnsafeSystemStatusControlServiceServer interface {
	mustEmbedUnimplementedSystemStatusControlServiceServer()
}

func RegisterSystemStatusControlServiceServer(s grpc.ServiceRegistrar, srv SystemStatusControlServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemStatusControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemStatusControlService_ServiceDesc, srv)
}

func _SystemStatusControlService_GetSystemStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemStatusControlServiceServer).GetSystemStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemStatusControlService_GetSystemStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemStatusControlServiceServer).GetSystemStats(ctx, req.(*SystemStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemStatusControlService_ServiceDesc is the grpc.ServiceDesc for SystemStatusControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemStatusControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoforward.SystemStatusControlService",
	HandlerType: (*SystemStatusControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemStats",
			Handler:    _SystemStatusControlService_GetSystemStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoforward.proto",
}
