// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: autoforward.proto

package autoforwardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoutingType int32

const (
	RoutingType_ROUTING_UNKNOWN    RoutingType = 0
	RoutingType_CHANNEL_TO_CHANNEL RoutingType = 1
	RoutingType_PV_TO_PV           RoutingType = 2
	RoutingType_CHANNEL_TO_PV      RoutingType = 3
	RoutingType_PV_TO_CHANNEL      RoutingType = 4
)

// Enum value maps for RoutingType.
var (
	RoutingType_name = map[int32]string{
		0: "ROUTING_UNKNOWN",
		1: "CHANNEL_TO_CHANNEL",
		2: "PV_TO_PV",
		3: "CHANNEL_TO_PV",
		4: "PV_TO_CHANNEL",
	}
	RoutingType_value = map[string]int32{
		"ROUTING_UNKNOWN":    0,
		"CHANNEL_TO_CHANNEL": 1,
		"PV_TO_PV":           2,
		"CHANNEL_TO_PV":      3,
		"PV_TO_CHANNEL":      4,
	}
)

func (x RoutingType) Enum() *RoutingType {
	p := new(RoutingType)
	*p = x
	return p
}

func (x RoutingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutingType) Descriptor() protoreflect.EnumDescriptor {
	return file_autoforward_proto_enumTypes[0].Descriptor()
}

func (RoutingType) Type() protoreflect.EnumType {
	return &file_autoforward_proto_enumTypes[0]
}

func (x RoutingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutingType.Descriptor instead.
func (RoutingType) EnumDescriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{0}
}

type ForwardMode int32

const (
	ForwardMode_FORWARD_MODE_UNKNOWN ForwardMode = 0
	ForwardMode_DIRECT_FORWARD       ForwardMode = 1 // Telegram native forward (keeps header)
	ForwardMode_COPY_MESSAGE         ForwardMode = 2 // Clean copy without sender header
)

// Enum value maps for ForwardMode.
var (
	ForwardMode_name = map[int32]string{
		0: "FORWARD_MODE_UNKNOWN",
		1: "DIRECT_FORWARD",
		2: "COPY_MESSAGE",
	}
	ForwardMode_value = map[string]int32{
		"FORWARD_MODE_UNKNOWN": 0,
		"DIRECT_FORWARD":       1,
		"COPY_MESSAGE":         2,
	}
)

func (x ForwardMode) Enum() *ForwardMode {
	p := new(ForwardMode)
	*p = x
	return p
}

func (x ForwardMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForwardMode) Descriptor() protoreflect.EnumDescriptor {
	return file_autoforward_proto_enumTypes[1].Descriptor()
}

func (ForwardMode) Type() protoreflect.EnumType {
	return &file_autoforward_proto_enumTypes[1]
}

func (x ForwardMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForwardMode.Descriptor instead.
func (ForwardMode) EnumDescriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{1}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_autoforward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsAuthorized  bool                   `protobuf:"varint,7,opt,name=is_authorized,json=isAuthorized,proto3" json:"is_authorized,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_autoforward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{1}
}

func (x *SessionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SessionInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SessionInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SessionInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *SessionInfo) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

func (x *SessionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_autoforward_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{2}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_autoforward_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type StartLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoginRequest) Reset() {
	*x = StartLoginRequest{}
	mi := &file_autoforward_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginRequest) ProtoMessage() {}

func (x *StartLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginRequest.ProtoReflect.Descriptor instead.
func (*StartLoginRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{4}
}

func (x *StartLoginRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type StartLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PhoneCodeHash string                 `protobuf:"bytes,2,opt,name=phone_code_hash,json=phoneCodeHash,proto3" json:"phone_code_hash,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoginResponse) Reset() {
	*x = StartLoginResponse{}
	mi := &file_autoforward_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginResponse) ProtoMessage() {}

func (x *StartLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginResponse.ProtoReflect.Descriptor instead.
func (*StartLoginResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{5}
}

func (x *StartLoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartLoginResponse) GetPhoneCodeHash() string {
	if x != nil {
		return x.PhoneCodeHash
	}
	return ""
}

func (x *StartLoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubmitCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PhoneCodeHash string                 `protobuf:"bytes,2,opt,name=phone_code_hash,json=phoneCodeHash,proto3" json:"phone_code_hash,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCodeRequest) Reset() {
	*x = SubmitCodeRequest{}
	mi := &file_autoforward_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCodeRequest) ProtoMessage() {}

func (x *SubmitCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCodeRequest.ProtoReflect.Descriptor instead.
func (*SubmitCodeRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitCodeRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SubmitCodeRequest) GetPhoneCodeHash() string {
	if x != nil {
		return x.PhoneCodeHash
	}
	return ""
}

func (x *SubmitCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SubmitCodeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RequiresPassword bool                   `protobuf:"varint,2,opt,name=requires_password,json=requiresPassword,proto3" json:"requires_password,omitempty"`
	SessionId        string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitCodeResponse) Reset() {
	*x = SubmitCodeResponse{}
	mi := &file_autoforward_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCodeResponse) ProtoMessage() {}

func (x *SubmitCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCodeResponse.ProtoReflect.Descriptor instead.
func (*SubmitCodeResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitCodeResponse) GetRequiresPassword() bool {
	if x != nil {
		return x.RequiresPassword
	}
	return false
}

func (x *SubmitCodeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubmitPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PhoneCodeHash string                 `protobuf:"bytes,2,opt,name=phone_code_hash,json=phoneCodeHash,proto3" json:"phone_code_hash,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPasswordRequest) Reset() {
	*x = SubmitPasswordRequest{}
	mi := &file_autoforward_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPasswordRequest) ProtoMessage() {}

func (x *SubmitPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPasswordRequest.ProtoReflect.Descriptor instead.
func (*SubmitPasswordRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitPasswordRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SubmitPasswordRequest) GetPhoneCodeHash() string {
	if x != nil {
		return x.PhoneCodeHash
	}
	return ""
}

func (x *SubmitPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SubmitPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPasswordResponse) Reset() {
	*x = SubmitPasswordResponse{}
	mi := &file_autoforward_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPasswordResponse) ProtoMessage() {}

func (x *SubmitPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPasswordResponse.ProtoReflect.Descriptor instead.
func (*SubmitPasswordResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitPasswordResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BackupSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSessionRequest) Reset() {
	*x = BackupSessionRequest{}
	mi := &file_autoforward_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSessionRequest) ProtoMessage() {}

func (x *BackupSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSessionRequest.ProtoReflect.Descriptor instead.
func (*BackupSessionRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{10}
}

func (x *BackupSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type BackupSessionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EncryptedSessionData string                 `protobuf:"bytes,2,opt,name=encrypted_session_data,json=encryptedSessionData,proto3" json:"encrypted_session_data,omitempty"`
	Checksum             string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BackupSessionResponse) Reset() {
	*x = BackupSessionResponse{}
	mi := &file_autoforward_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSessionResponse) ProtoMessage() {}

func (x *BackupSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSessionResponse.ProtoReflect.Descriptor instead.
func (*BackupSessionResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{11}
}

func (x *BackupSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BackupSessionResponse) GetEncryptedSessionData() string {
	if x != nil {
		return x.EncryptedSessionData
	}
	return ""
}

func (x *BackupSessionResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *BackupSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestoreSessionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EncryptedSessionData string                 `protobuf:"bytes,1,opt,name=encrypted_session_data,json=encryptedSessionData,proto3" json:"encrypted_session_data,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RestoreSessionRequest) Reset() {
	*x = RestoreSessionRequest{}
	mi := &file_autoforward_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSessionRequest) ProtoMessage() {}

func (x *RestoreSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSessionRequest.ProtoReflect.Descriptor instead.
func (*RestoreSessionRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{12}
}

func (x *RestoreSessionRequest) GetEncryptedSessionData() string {
	if x != nil {
		return x.EncryptedSessionData
	}
	return ""
}

type RestoreSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSessionResponse) Reset() {
	*x = RestoreSessionResponse{}
	mi := &file_autoforward_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSessionResponse) ProtoMessage() {}

func (x *RestoreSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSessionResponse.ProtoReflect.Descriptor instead.
func (*RestoreSessionResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{13}
}

func (x *RestoreSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RestoreSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TerminateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionRequest) Reset() {
	*x = TerminateSessionRequest{}
	mi := &file_autoforward_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionRequest) ProtoMessage() {}

func (x *TerminateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionRequest.ProtoReflect.Descriptor instead.
func (*TerminateSessionRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{14}
}

func (x *TerminateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ForwardRule struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId             string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SourceChatId          string                 `protobuf:"bytes,3,opt,name=source_chat_id,json=sourceChatId,proto3" json:"source_chat_id,omitempty"`
	SourceChatName        string                 `protobuf:"bytes,4,opt,name=source_chat_name,json=sourceChatName,proto3" json:"source_chat_name,omitempty"`
	TargetChatId          string                 `protobuf:"bytes,5,opt,name=target_chat_id,json=targetChatId,proto3" json:"target_chat_id,omitempty"`
	TargetChatName        string                 `protobuf:"bytes,6,opt,name=target_chat_name,json=targetChatName,proto3" json:"target_chat_name,omitempty"`
	RoutingType           RoutingType            `protobuf:"varint,7,opt,name=routing_type,json=routingType,proto3,enum=autoforward.RoutingType" json:"routing_type,omitempty"`
	ForwardMode           ForwardMode            `protobuf:"varint,8,opt,name=forward_mode,json=forwardMode,proto3,enum=autoforward.ForwardMode" json:"forward_mode,omitempty"`
	IsActive              bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	FilterRuleId          string                 `protobuf:"bytes,10,opt,name=filter_rule_id,json=filterRuleId,proto3" json:"filter_rule_id,omitempty"`
	AiConfigId            string                 `protobuf:"bytes,11,opt,name=ai_config_id,json=aiConfigId,proto3" json:"ai_config_id,omitempty"`
	RemoveLinks           bool                   `protobuf:"varint,12,opt,name=remove_links,json=removeLinks,proto3" json:"remove_links,omitempty"`
	CustomCaptionTemplate string                 `protobuf:"bytes,13,opt,name=custom_caption_template,json=customCaptionTemplate,proto3" json:"custom_caption_template,omitempty"`
	CreatedAt             int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             int64                  `protobuf:"varint,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ForwardRule) Reset() {
	*x = ForwardRule{}
	mi := &file_autoforward_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRule) ProtoMessage() {}

func (x *ForwardRule) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRule.ProtoReflect.Descriptor instead.
func (*ForwardRule) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{15}
}

func (x *ForwardRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ForwardRule) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ForwardRule) GetSourceChatId() string {
	if x != nil {
		return x.SourceChatId
	}
	return ""
}

func (x *ForwardRule) GetSourceChatName() string {
	if x != nil {
		return x.SourceChatName
	}
	return ""
}

func (x *ForwardRule) GetTargetChatId() string {
	if x != nil {
		return x.TargetChatId
	}
	return ""
}

func (x *ForwardRule) GetTargetChatName() string {
	if x != nil {
		return x.TargetChatName
	}
	return ""
}

func (x *ForwardRule) GetRoutingType() RoutingType {
	if x != nil {
		return x.RoutingType
	}
	return RoutingType_ROUTING_UNKNOWN
}

func (x *ForwardRule) GetForwardMode() ForwardMode {
	if x != nil {
		return x.ForwardMode
	}
	return ForwardMode_FORWARD_MODE_UNKNOWN
}

func (x *ForwardRule) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ForwardRule) GetFilterRuleId() string {
	if x != nil {
		return x.FilterRuleId
	}
	return ""
}

func (x *ForwardRule) GetAiConfigId() string {
	if x != nil {
		return x.AiConfigId
	}
	return ""
}

func (x *ForwardRule) GetRemoveLinks() bool {
	if x != nil {
		return x.RemoveLinks
	}
	return false
}

func (x *ForwardRule) GetCustomCaptionTemplate() string {
	if x != nil {
		return x.CustomCaptionTemplate
	}
	return ""
}

func (x *ForwardRule) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ForwardRule) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *ForwardRule           `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_autoforward_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{16}
}

func (x *CreateRuleRequest) GetRule() *ForwardRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type UpdateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *ForwardRule           `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_autoforward_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateRuleRequest) GetRule() *ForwardRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_autoforward_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_autoforward_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{19}
}

func (x *ListRulesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*ForwardRule         `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_autoforward_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{20}
}

func (x *ListRulesResponse) GetRules() []*ForwardRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type FilterRule struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WhitelistKeywords   []string               `protobuf:"bytes,3,rep,name=whitelist_keywords,json=whitelistKeywords,proto3" json:"whitelist_keywords,omitempty"`
	BlacklistKeywords   []string               `protobuf:"bytes,4,rep,name=blacklist_keywords,json=blacklistKeywords,proto3" json:"blacklist_keywords,omitempty"`
	RegexPatterns       []string               `protobuf:"bytes,5,rep,name=regex_patterns,json=regexPatterns,proto3" json:"regex_patterns,omitempty"`
	AllowedMediaTypes   []string               `protobuf:"bytes,6,rep,name=allowed_media_types,json=allowedMediaTypes,proto3" json:"allowed_media_types,omitempty"` // text, photo, video, document, voice, audio, animation
	BlockedMediaTypes   []string               `protobuf:"bytes,7,rep,name=blocked_media_types,json=blockedMediaTypes,proto3" json:"blocked_media_types,omitempty"`
	DropServiceMessages bool                   `protobuf:"varint,8,opt,name=drop_service_messages,json=dropServiceMessages,proto3" json:"drop_service_messages,omitempty"`
	MinMessageLength    int64                  `protobuf:"varint,9,opt,name=min_message_length,json=minMessageLength,proto3" json:"min_message_length,omitempty"`
	MaxMessageLength    int64                  `protobuf:"varint,10,opt,name=max_message_length,json=maxMessageLength,proto3" json:"max_message_length,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FilterRule) Reset() {
	*x = FilterRule{}
	mi := &file_autoforward_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRule) ProtoMessage() {}

func (x *FilterRule) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRule.ProtoReflect.Descriptor instead.
func (*FilterRule) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{21}
}

func (x *FilterRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FilterRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilterRule) GetWhitelistKeywords() []string {
	if x != nil {
		return x.WhitelistKeywords
	}
	return nil
}

func (x *FilterRule) GetBlacklistKeywords() []string {
	if x != nil {
		return x.BlacklistKeywords
	}
	return nil
}

func (x *FilterRule) GetRegexPatterns() []string {
	if x != nil {
		return x.RegexPatterns
	}
	return nil
}

func (x *FilterRule) GetAllowedMediaTypes() []string {
	if x != nil {
		return x.AllowedMediaTypes
	}
	return nil
}

func (x *FilterRule) GetBlockedMediaTypes() []string {
	if x != nil {
		return x.BlockedMediaTypes
	}
	return nil
}

func (x *FilterRule) GetDropServiceMessages() bool {
	if x != nil {
		return x.DropServiceMessages
	}
	return false
}

func (x *FilterRule) GetMinMessageLength() int64 {
	if x != nil {
		return x.MinMessageLength
	}
	return 0
}

func (x *FilterRule) GetMaxMessageLength() int64 {
	if x != nil {
		return x.MaxMessageLength
	}
	return 0
}

type CreateFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *FilterRule            `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFilterRequest) Reset() {
	*x = CreateFilterRequest{}
	mi := &file_autoforward_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilterRequest) ProtoMessage() {}

func (x *CreateFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilterRequest.ProtoReflect.Descriptor instead.
func (*CreateFilterRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{22}
}

func (x *CreateFilterRequest) GetFilter() *FilterRule {
	if x != nil {
		return x.Filter
	}
	return nil
}

type UpdateFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *FilterRule            `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFilterRequest) Reset() {
	*x = UpdateFilterRequest{}
	mi := &file_autoforward_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFilterRequest) ProtoMessage() {}

func (x *UpdateFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFilterRequest.ProtoReflect.Descriptor instead.
func (*UpdateFilterRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateFilterRequest) GetFilter() *FilterRule {
	if x != nil {
		return x.Filter
	}
	return nil
}

type DeleteFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFilterRequest) Reset() {
	*x = DeleteFilterRequest{}
	mi := &file_autoforward_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilterRequest) ProtoMessage() {}

func (x *DeleteFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilterRequest.ProtoReflect.Descriptor instead.
func (*DeleteFilterRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteFilterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFiltersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFiltersRequest) Reset() {
	*x = ListFiltersRequest{}
	mi := &file_autoforward_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFiltersRequest) ProtoMessage() {}

func (x *ListFiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFiltersRequest.ProtoReflect.Descriptor instead.
func (*ListFiltersRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{25}
}

type ListFiltersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*FilterRule          `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFiltersResponse) Reset() {
	*x = ListFiltersResponse{}
	mi := &file_autoforward_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFiltersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFiltersResponse) ProtoMessage() {}

func (x *ListFiltersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFiltersResponse.ProtoReflect.Descriptor instead.
func (*ListFiltersResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{26}
}

func (x *ListFiltersResponse) GetFilters() []*FilterRule {
	if x != nil {
		return x.Filters
	}
	return nil
}

type AIConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider           string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`              // openai, anthropic, gemini, groq, deepseek, 9router, openrouter, custom
	Model              string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`                    // gpt-4o-mini, claude-3-5-sonnet, gemini-2.0-flash, etc.
	ApiKey             string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`    // Encrypted or masked
	BaseUrl            string                 `protobuf:"bytes,6,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"` // Optional custom endpoint
	SystemPrompt       string                 `protobuf:"bytes,7,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	UserPromptTemplate string                 `protobuf:"bytes,8,opt,name=user_prompt_template,json=userPromptTemplate,proto3" json:"user_prompt_template,omitempty"` // e.g. "Rewrite this post in professional tone: {text}"
	Temperature        float64                `protobuf:"fixed64,9,opt,name=temperature,proto3" json:"temperature,omitempty"`
	IsEnabled          bool                   `protobuf:"varint,10,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	TargetLanguage     string                 `protobuf:"bytes,11,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"` // en, fa, ru, zh, etc.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AIConfig) Reset() {
	*x = AIConfig{}
	mi := &file_autoforward_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIConfig) ProtoMessage() {}

func (x *AIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIConfig.ProtoReflect.Descriptor instead.
func (*AIConfig) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{27}
}

func (x *AIConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AIConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AIConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AIConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AIConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AIConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *AIConfig) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *AIConfig) GetUserPromptTemplate() string {
	if x != nil {
		return x.UserPromptTemplate
	}
	return ""
}

func (x *AIConfig) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AIConfig) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *AIConfig) GetTargetLanguage() string {
	if x != nil {
		return x.TargetLanguage
	}
	return ""
}

type CreateAIConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AIConfig              `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAIConfigRequest) Reset() {
	*x = CreateAIConfigRequest{}
	mi := &file_autoforward_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAIConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAIConfigRequest) ProtoMessage() {}

func (x *CreateAIConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAIConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateAIConfigRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{28}
}

func (x *CreateAIConfigRequest) GetConfig() *AIConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateAIConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AIConfig              `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAIConfigRequest) Reset() {
	*x = UpdateAIConfigRequest{}
	mi := &file_autoforward_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAIConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAIConfigRequest) ProtoMessage() {}

func (x *UpdateAIConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAIConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateAIConfigRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateAIConfigRequest) GetConfig() *AIConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteAIConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAIConfigRequest) Reset() {
	*x = DeleteAIConfigRequest{}
	mi := &file_autoforward_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAIConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAIConfigRequest) ProtoMessage() {}

func (x *DeleteAIConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAIConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteAIConfigRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteAIConfigRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAIConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAIConfigsRequest) Reset() {
	*x = ListAIConfigsRequest{}
	mi := &file_autoforward_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAIConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAIConfigsRequest) ProtoMessage() {}

func (x *ListAIConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAIConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListAIConfigsRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{31}
}

type ListAIConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*AIConfig            `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAIConfigsResponse) Reset() {
	*x = ListAIConfigsResponse{}
	mi := &file_autoforward_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAIConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAIConfigsResponse) ProtoMessage() {}

func (x *ListAIConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAIConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListAIConfigsResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{32}
}

func (x *ListAIConfigsResponse) GetConfigs() []*AIConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type TestAIRewriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AiConfigId    string                 `protobuf:"bytes,1,opt,name=ai_config_id,json=aiConfigId,proto3" json:"ai_config_id,omitempty"`
	SampleText    string                 `protobuf:"bytes,2,opt,name=sample_text,json=sampleText,proto3" json:"sample_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAIRewriteRequest) Reset() {
	*x = TestAIRewriteRequest{}
	mi := &file_autoforward_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAIRewriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAIRewriteRequest) ProtoMessage() {}

func (x *TestAIRewriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAIRewriteRequest.ProtoReflect.Descriptor instead.
func (*TestAIRewriteRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{33}
}

func (x *TestAIRewriteRequest) GetAiConfigId() string {
	if x != nil {
		return x.AiConfigId
	}
	return ""
}

func (x *TestAIRewriteRequest) GetSampleText() string {
	if x != nil {
		return x.SampleText
	}
	return ""
}

type TestAIRewriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RewrittenText string                 `protobuf:"bytes,2,opt,name=rewritten_text,json=rewrittenText,proto3" json:"rewritten_text,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAIRewriteResponse) Reset() {
	*x = TestAIRewriteResponse{}
	mi := &file_autoforward_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAIRewriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAIRewriteResponse) ProtoMessage() {}

func (x *TestAIRewriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAIRewriteResponse.ProtoReflect.Descriptor instead.
func (*TestAIRewriteResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{34}
}

func (x *TestAIRewriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestAIRewriteResponse) GetRewrittenText() string {
	if x != nil {
		return x.RewrittenText
	}
	return ""
}

func (x *TestAIRewriteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SystemStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatsRequest) Reset() {
	*x = SystemStatsRequest{}
	mi := &file_autoforward_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsRequest) ProtoMessage() {}

func (x *SystemStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsRequest.ProtoReflect.Descriptor instead.
func (*SystemStatsRequest) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{35}
}

type SystemStatsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CoreRunning            bool                   `protobuf:"varint,1,opt,name=core_running,json=coreRunning,proto3" json:"core_running,omitempty"`
	UptimeSeconds          int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveSessionsCount    int32                  `protobuf:"varint,3,opt,name=active_sessions_count,json=activeSessionsCount,proto3" json:"active_sessions_count,omitempty"`
	ActiveRulesCount       int32                  `protobuf:"varint,4,opt,name=active_rules_count,json=activeRulesCount,proto3" json:"active_rules_count,omitempty"`
	TotalMessagesProcessed int64                  `protobuf:"varint,5,opt,name=total_messages_processed,json=totalMessagesProcessed,proto3" json:"total_messages_processed,omitempty"`
	TotalMessagesForwarded int64                  `protobuf:"varint,6,opt,name=total_messages_forwarded,json=totalMessagesForwarded,proto3" json:"total_messages_forwarded,omitempty"`
	TotalMessagesFiltered  int64                  `protobuf:"varint,7,opt,name=total_messages_filtered,json=totalMessagesFiltered,proto3" json:"total_messages_filtered,omitempty"`
	TotalMessagesRewritten int64                  `protobuf:"varint,8,opt,name=total_messages_rewritten,json=totalMessagesRewritten,proto3" json:"total_messages_rewritten,omitempty"`
	BotUsername            string                 `protobuf:"bytes,9,opt,name=bot_username,json=botUsername,proto3" json:"bot_username,omitempty"`
	Version                string                 `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SystemStatsResponse) Reset() {
	*x = SystemStatsResponse{}
	mi := &file_autoforward_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsResponse) ProtoMessage() {}

func (x *SystemStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoforward_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsResponse.ProtoReflect.Descriptor instead.
func (*SystemStatsResponse) Descriptor() ([]byte, []int) {
	return file_autoforward_proto_rawDescGZIP(), []int{36}
}

func (x *SystemStatsResponse) GetCoreRunning() bool {
	if x != nil {
		return x.CoreRunning
	}
	return false
}

func (x *SystemStatsResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemStatsResponse) GetActiveSessionsCount() int32 {
	if x != nil {
		return x.ActiveSessionsCount
	}
	return 0
}

func (x *SystemStatsResponse) GetActiveRulesCount() int32 {
	if x != nil {
		return x.ActiveRulesCount
	}
	return 0
}

func (x *SystemStatsResponse) GetTotalMessagesProcessed() int64 {
	if x != nil {
		return x.TotalMessagesProcessed
	}
	return 0
}

func (x *SystemStatsResponse) GetTotalMessagesForwarded() int64 {
	if x != nil {
		return x.TotalMessagesForwarded
	}
	return 0
}

func (x *SystemStatsResponse) GetTotalMessagesFiltered() int64 {
	if x != nil {
		return x.TotalMessagesFiltered
	}
	return 0
}

func (x *SystemStatsResponse) GetTotalMessagesRewritten() int64 {
	if x != nil {
		return x.TotalMessagesRewritten
	}
	return 0
}

func (x *SystemStatsResponse) GetBotUsername() string {
	if x != nil {
		return x.BotUsername
	}
	return ""
}

func (x *SystemStatsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_autoforward_proto protoreflect.FileDescriptor

const file_autoforward_proto_rawDesc = "" +
	"\n" +
	"\x11autoforward.proto\x12\vautoforward\"c\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"\x94\x02\n" +
	"\vSessionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12#\n" +
	"\ris_authorized\x18\a \x01(\bR\fisAuthorized\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"\x15\n" +
	"\x13ListSessionsRequest\"L\n" +
	"\x14ListSessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.autoforward.SessionInfoR\bsessions\"6\n" +
	"\x11StartLoginRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"p\n" +
	"\x12StartLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fphone_code_hash\x18\x02 \x01(\tR\rphoneCodeHash\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"r\n" +
	"\x11SubmitCodeRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12&\n" +
	"\x0fphone_code_hash\x18\x02 \x01(\tR\rphoneCodeHash\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\x94\x01\n" +
	"\x12SubmitCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x11requires_password\x18\x02 \x01(\bR\x10requiresPassword\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"~\n" +
	"\x15SubmitPasswordRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12&\n" +
	"\x0fphone_code_hash\x18\x02 \x01(\tR\rphoneCodeHash\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"k\n" +
	"\x16SubmitPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"5\n" +
	"\x14BackupSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x9d\x01\n" +
	"\x15BackupSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\x16encrypted_session_data\x18\x02 \x01(\tR\x14encryptedSessionData\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"M\n" +
	"\x15RestoreSessionRequest\x124\n" +
	"\x16encrypted_session_data\x18\x01 \x01(\tR\x14encryptedSessionData\"k\n" +
	"\x16RestoreSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"8\n" +
	"\x17TerminateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xd4\x04\n" +
	"\vForwardRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12$\n" +
	"\x0esource_chat_id\x18\x03 \x01(\tR\fsourceChatId\x12(\n" +
	"\x10source_chat_name\x18\x04 \x01(\tR\x0esourceChatName\x12$\n" +
	"\x0etarget_chat_id\x18\x05 \x01(\tR\ftargetChatId\x12(\n" +
	"\x10target_chat_name\x18\x06 \x01(\tR\x0etargetChatName\x12;\n" +
	"\frouting_type\x18\a \x01(\x0e2\x18.autoforward.RoutingTypeR\vroutingType\x12;\n" +
	"\fforward_mode\x18\b \x01(\x0e2\x18.autoforward.ForwardModeR\vforwardMode\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12$\n" +
	"\x0efilter_rule_id\x18\n" +
	" \x01(\tR\ffilterRuleId\x12 \n" +
	"\fai_config_id\x18\v \x01(\tR\n" +
	"aiConfigId\x12!\n" +
	"\fremove_links\x18\f \x01(\bR\vremoveLinks\x126\n" +
	"\x17custom_caption_template\x18\r \x01(\tR\x15customCaptionTemplate\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x03R\tupdatedAt\"A\n" +
	"\x11CreateRuleRequest\x12,\n" +
	"\x04rule\x18\x01 \x01(\v2\x18.autoforward.ForwardRuleR\x04rule\"A\n" +
	"\x11UpdateRuleRequest\x12,\n" +
	"\x04rule\x18\x01 \x01(\v2\x18.autoforward.ForwardRuleR\x04rule\"#\n" +
	"\x11DeleteRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x10ListRulesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"C\n" +
	"\x11ListRulesResponse\x12.\n" +
	"\x05rules\x18\x01 \x03(\v2\x18.autoforward.ForwardRuleR\x05rules\"\xa5\x03\n" +
	"\n" +
	"FilterRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x12whitelist_keywords\x18\x03 \x03(\tR\x11whitelistKeywords\x12-\n" +
	"\x12blacklist_keywords\x18\x04 \x03(\tR\x11blacklistKeywords\x12%\n" +
	"\x0eregex_patterns\x18\x05 \x03(\tR\rregexPatterns\x12.\n" +
	"\x13allowed_media_types\x18\x06 \x03(\tR\x11allowedMediaTypes\x12.\n" +
	"\x13blocked_media_types\x18\a \x03(\tR\x11blockedMediaTypes\x122\n" +
	"\x15drop_service_messages\x18\b \x01(\bR\x13dropServiceMessages\x12,\n" +
	"\x12min_message_length\x18\t \x01(\x03R\x10minMessageLength\x12,\n" +
	"\x12max_message_length\x18\n" +
	" \x01(\x03R\x10maxMessageLength\"F\n" +
	"\x13CreateFilterRequest\x12/\n" +
	"\x06filter\x18\x01 \x01(\v2\x17.autoforward.FilterRuleR\x06filter\"F\n" +
	"\x13UpdateFilterRequest\x12/\n" +
	"\x06filter\x18\x01 \x01(\v2\x17.autoforward.FilterRuleR\x06filter\"%\n" +
	"\x13DeleteFilterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12ListFiltersRequest\"H\n" +
	"\x13ListFiltersResponse\x121\n" +
	"\afilters\x18\x01 \x03(\v2\x17.autoforward.FilterRuleR\afilters\"\xd5\x02\n" +
	"\bAIConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x06 \x01(\tR\abaseUrl\x12#\n" +
	"\rsystem_prompt\x18\a \x01(\tR\fsystemPrompt\x120\n" +
	"\x14user_prompt_template\x18\b \x01(\tR\x12userPromptTemplate\x12 \n" +
	"\vtemperature\x18\t \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\n" +
	" \x01(\bR\tisEnabled\x12'\n" +
	"\x0ftarget_language\x18\v \x01(\tR\x0etargetLanguage\"F\n" +
	"\x15CreateAIConfigRequest\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x15.autoforward.AIConfigR\x06config\"F\n" +
	"\x15UpdateAIConfigRequest\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x15.autoforward.AIConfigR\x06config\"'\n" +
	"\x15DeleteAIConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14ListAIConfigsRequest\"H\n" +
	"\x15ListAIConfigsResponse\x12/\n" +
	"\aconfigs\x18\x01 \x03(\v2\x15.autoforward.AIConfigR\aconfigs\"Y\n" +
	"\x14TestAIRewriteRequest\x12 \n" +
	"\fai_config_id\x18\x01 \x01(\tR\n" +
	"aiConfigId\x12\x1f\n" +
	"\vsample_text\x18\x02 \x01(\tR\n" +
	"sampleText\"}\n" +
	"\x15TestAIRewriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0erewritten_text\x18\x02 \x01(\tR\rrewrittenText\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x14\n" +
	"\x12SystemStatsRequest\"\xe4\x03\n" +
	"\x13SystemStatsResponse\x12!\n" +
	"\fcore_running\x18\x01 \x01(\bR\vcoreRunning\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x122\n" +
	"\x15active_sessions_count\x18\x03 \x01(\x05R\x13activeSessionsCount\x12,\n" +
	"\x12active_rules_count\x18\x04 \x01(\x05R\x10activeRulesCount\x128\n" +
	"\x18total_messages_processed\x18\x05 \x01(\x03R\x16totalMessagesProcessed\x128\n" +
	"\x18total_messages_forwarded\x18\x06 \x01(\x03R\x16totalMessagesForwarded\x126\n" +
	"\x17total_messages_filtered\x18\a \x01(\x03R\x15totalMessagesFiltered\x128\n" +
	"\x18total_messages_rewritten\x18\b \x01(\x03R\x16totalMessagesRewritten\x12!\n" +
	"\fbot_username\x18\t \x01(\tR\vbotUsername\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversion*n\n" +
	"\vRoutingType\x12\x13\n" +
	"\x0fROUTING_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12CHANNEL_TO_CHANNEL\x10\x01\x12\f\n" +
	"\bPV_TO_PV\x10\x02\x12\x11\n" +
	"\rCHANNEL_TO_PV\x10\x03\x12\x11\n" +
	"\rPV_TO_CHANNEL\x10\x04*M\n" +
	"\vForwardMode\x12\x18\n" +
	"\x14FORWARD_MODE_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eDIRECT_FORWARD\x10\x01\x12\x10\n" +
	"\fCOPY_MESSAGE\x10\x022\xef\x04\n" +
	"\x15SessionControlService\x12S\n" +
	"\fListSessions\x12 .autoforward.ListSessionsRequest\x1a!.autoforward.ListSessionsResponse\x12M\n" +
	"\n" +
	"StartLogin\x12\x1e.autoforward.StartLoginRequest\x1a\x1f.autoforward.StartLoginResponse\x12M\n" +
	"\n" +
	"SubmitCode\x12\x1e.autoforward.SubmitCodeRequest\x1a\x1f.autoforward.SubmitCodeResponse\x12Y\n" +
	"\x0eSubmitPassword\x12\".autoforward.SubmitPasswordRequest\x1a#.autoforward.SubmitPasswordResponse\x12V\n" +
	"\rBackupSession\x12!.autoforward.BackupSessionRequest\x1a\".autoforward.BackupSessionResponse\x12Y\n" +
	"\x0eRestoreSession\x12\".autoforward.RestoreSessionRequest\x1a#.autoforward.RestoreSessionResponse\x12U\n" +
	"\x10TerminateSession\x12$.autoforward.TerminateSessionRequest\x1a\x1b.autoforward.StatusResponse2\xc2\x02\n" +
	"\x19ForwardRuleControlService\x12J\n" +
	"\tListRules\x12\x1d.autoforward.ListRulesRequest\x1a\x1e.autoforward.ListRulesResponse\x12F\n" +
	"\n" +
	"CreateRule\x12\x1e.autoforward.CreateRuleRequest\x1a\x18.autoforward.ForwardRule\x12F\n" +
	"\n" +
	"UpdateRule\x12\x1e.autoforward.UpdateRuleRequest\x1a\x18.autoforward.ForwardRule\x12I\n" +
	"\n" +
	"DeleteRule\x12\x1e.autoforward.DeleteRuleRequest\x1a\x1b.autoforward.StatusResponse2\xcd\x02\n" +
	"\x14FilterControlService\x12P\n" +
	"\vListFilters\x12\x1f.autoforward.ListFiltersRequest\x1a .autoforward.ListFiltersResponse\x12I\n" +
	"\fCreateFilter\x12 .autoforward.CreateFilterRequest\x1a\x17.autoforward.FilterRule\x12I\n" +
	"\fUpdateFilter\x12 .autoforward.UpdateFilterRequest\x1a\x17.autoforward.FilterRule\x12M\n" +
	"\fDeleteFilter\x12 .autoforward.DeleteFilterRequest\x1a\x1b.autoforward.StatusResponse2\xaf\x03\n" +
	"\x10AIControlService\x12V\n" +
	"\rListAIConfigs\x12!.autoforward.ListAIConfigsRequest\x1a\".autoforward.ListAIConfigsResponse\x12K\n" +
	"\x0eCreateAIConfig\x12\".autoforward.CreateAIConfigRequest\x1a\x15.autoforward.AIConfig\x12K\n" +
	"\x0eUpdateAIConfig\x12\".autoforward.UpdateAIConfigRequest\x1a\x15.autoforward.AIConfig\x12Q\n" +
	"\x0eDeleteAIConfig\x12\".autoforward.DeleteAIConfigRequest\x1a\x1b.autoforward.StatusResponse\x12V\n" +
	"\rTestAIRewrite\x12!.autoforward.TestAIRewriteRequest\x1a\".autoforward.TestAIRewriteResponse2q\n" +
	"\x1aSystemStatusControlService\x12S\n" +
	"\x0eGetSystemStats\x12\x1f.autoforward.SystemStatsRequest\x1a .autoforward.SystemStatsResponseB%Z#autoforward/api/proto;autoforwardpbb\x06proto3"

var (
	file_autoforward_proto_rawDescOnce sync.Once
	file_autoforward_proto_rawDescData []byte
)

func file_autoforward_proto_rawDescGZIP() []byte {
	file_autoforward_proto_rawDescOnce.Do(func() {
		file_autoforward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_autoforward_proto_rawDesc), len(file_autoforward_proto_rawDesc)))
	})
	return file_autoforward_proto_rawDescData
}

var file_autoforward_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_autoforward_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_autoforward_proto_goTypes = []any{
	(RoutingType)(0),                // 0: autoforward.RoutingType
	(ForwardMode)(0),                // 1: autoforward.ForwardMode
	(*StatusResponse)(nil),          // 2: autoforward.StatusResponse
	(*SessionInfo)(nil),             // 3: autoforward.SessionInfo
	(*ListSessionsRequest)(nil),     // 4: autoforward.ListSessionsRequest
	(*ListSessionsResponse)(nil),    // 5: autoforward.ListSessionsResponse
	(*StartLoginRequest)(nil),       // 6: autoforward.StartLoginRequest
	(*StartLoginResponse)(nil),      // 7: autoforward.StartLoginResponse
	(*SubmitCodeRequest)(nil),       // 8: autoforward.SubmitCodeRequest
	(*SubmitCodeResponse)(nil),      // 9: autoforward.SubmitCodeResponse
	(*SubmitPasswordRequest)(nil),   // 10: autoforward.SubmitPasswordRequest
	(*SubmitPasswordResponse)(nil),  // 11: autoforward.SubmitPasswordResponse
	(*BackupSessionRequest)(nil),    // 12: autoforward.BackupSessionRequest
	(*BackupSessionResponse)(nil),   // 13: autoforward.BackupSessionResponse
	(*RestoreSessionRequest)(nil),   // 14: autoforward.RestoreSessionRequest
	(*RestoreSessionResponse)(nil),  // 15: autoforward.RestoreSessionResponse
	(*TerminateSessionRequest)(nil), // 16: autoforward.TerminateSessionRequest
	(*ForwardRule)(nil),             // 17: autoforward.ForwardRule
	(*CreateRuleRequest)(nil),       // 18: autoforward.CreateRuleRequest
	(*UpdateRuleRequest)(nil),       // 19: autoforward.UpdateRuleRequest
	(*DeleteRuleRequest)(nil),       // 20: autoforward.DeleteRuleRequest
	(*ListRulesRequest)(nil),        // 21: autoforward.ListRulesRequest
	(*ListRulesResponse)(nil),       // 22: autoforward.ListRulesResponse
	(*FilterRule)(nil),              // 23: autoforward.FilterRule
	(*CreateFilterRequest)(nil),     // 24: autoforward.CreateFilterRequest
	(*UpdateFilterRequest)(nil),     // 25: autoforward.UpdateFilterRequest
	(*DeleteFilterRequest)(nil),     // 26: autoforward.DeleteFilterRequest
	(*ListFiltersRequest)(nil),      // 27: autoforward.ListFiltersRequest
	(*ListFiltersResponse)(nil),     // 28: autoforward.ListFiltersResponse
	(*AIConfig)(nil),                // 29: autoforward.AIConfig
	(*CreateAIConfigRequest)(nil),   // 30: autoforward.CreateAIConfigRequest
	(*UpdateAIConfigRequest)(nil),   // 31: autoforward.UpdateAIConfigRequest
	(*DeleteAIConfigRequest)(nil),   // 32: autoforward.DeleteAIConfigRequest
	(*ListAIConfigsRequest)(nil),    // 33: autoforward.ListAIConfigsRequest
	(*ListAIConfigsResponse)(nil),   // 34: autoforward.ListAIConfigsResponse
	(*TestAIRewriteRequest)(nil),    // 35: autoforward.TestAIRewriteRequest
	(*TestAIRewriteResponse)(nil),   // 36: autoforward.TestAIRewriteResponse
	(*SystemStatsRequest)(nil),      // 37: autoforward.SystemStatsRequest
	(*SystemStatsResponse)(nil),     // 38: autoforward.SystemStatsResponse
}
var file_autoforward_proto_depIdxs = []int32{
	3,  // 0: autoforward.ListSessionsResponse.sessions:type_name -> autoforward.SessionInfo
	0,  // 1: autoforward.ForwardRule.routing_type:type_name -> autoforward.RoutingType
	1,  // 2: autoforward.ForwardRule.forward_mode:type_name -> autoforward.ForwardMode
	17, // 3: autoforward.CreateRuleRequest.rule:type_name -> autoforward.ForwardRule
	17, // 4: autoforward.UpdateRuleRequest.rule:type_name -> autoforward.ForwardRule
	17, // 5: autoforward.ListRulesResponse.rules:type_name -> autoforward.ForwardRule
	23, // 6: autoforward.CreateFilterRequest.filter:type_name -> autoforward.FilterRule
	23, // 7: autoforward.UpdateFilterRequest.filter:type_name -> autoforward.FilterRule
	23, // 8: autoforward.ListFiltersResponse.filters:type_name -> autoforward.FilterRule
	29, // 9: autoforward.CreateAIConfigRequest.config:type_name -> autoforward.AIConfig
	29, // 10: autoforward.UpdateAIConfigRequest.config:type_name -> autoforward.AIConfig
	29, // 11: autoforward.ListAIConfigsResponse.configs:type_name -> autoforward.AIConfig
	4,  // 12: autoforward.SessionControlService.ListSessions:input_type -> autoforward.ListSessionsRequest
	6,  // 13: autoforward.SessionControlService.StartLogin:input_type -> autoforward.StartLoginRequest
	8,  // 14: autoforward.SessionControlService.SubmitCode:input_type -> autoforward.SubmitCodeRequest
	10, // 15: autoforward.SessionControlService.SubmitPassword:input_type -> autoforward.SubmitPasswordRequest
	12, // 16: autoforward.SessionControlService.BackupSession:input_type -> autoforward.BackupSessionRequest
	14, // 17: autoforward.SessionControlService.RestoreSession:input_type -> autoforward.RestoreSessionRequest
	16, // 18: autoforward.SessionControlService.TerminateSession:input_type -> autoforward.TerminateSessionRequest
	21, // 19: autoforward.ForwardRuleControlService.ListRules:input_type -> autoforward.ListRulesRequest
	18, // 20: autoforward.ForwardRuleControlService.CreateRule:input_type -> autoforward.CreateRuleRequest
	19, // 21: autoforward.ForwardRuleControlService.UpdateRule:input_type -> autoforward.UpdateRuleRequest
	20, // 22: autoforward.ForwardRuleControlService.DeleteRule:input_type -> autoforward.DeleteRuleRequest
	27, // 23: autoforward.FilterControlService.ListFilters:input_type -> autoforward.ListFiltersRequest
	24, // 24: autoforward.FilterControlService.CreateFilter:input_type -> autoforward.CreateFilterRequest
	25, // 25: autoforward.FilterControlService.UpdateFilter:input_type -> autoforward.UpdateFilterRequest
	26, // 26: autoforward.FilterControlService.DeleteFilter:input_type -> autoforward.DeleteFilterRequest
	33, // 27: autoforward.AIControlService.ListAIConfigs:input_type -> autoforward.ListAIConfigsRequest
	30, // 28: autoforward.AIControlService.CreateAIConfig:input_type -> autoforward.CreateAIConfigRequest
	31, // 29: autoforward.AIControlService.UpdateAIConfig:input_type -> autoforward.UpdateAIConfigRequest
	32, // 30: autoforward.AIControlService.DeleteAIConfig:input_type -> autoforward.DeleteAIConfigRequest
	35, // 31: autoforward.AIControlService.TestAIRewrite:input_type -> autoforward.TestAIRewriteRequest
	37, // 32: autoforward.SystemStatusControlService.GetSystemStats:input_type -> autoforward.SystemStatsRequest
	5,  // 33: autoforward.SessionControlService.ListSessions:output_type -> autoforward.ListSessionsResponse
	7,  // 34: autoforward.SessionControlService.StartLogin:output_type -> autoforward.StartLoginResponse
	9,  // 35: autoforward.SessionControlService.SubmitCode:output_type -> autoforward.SubmitCodeResponse
	11, // 36: autoforward.SessionControlService.SubmitPassword:output_type -> autoforward.SubmitPasswordResponse
	13, // 37: autoforward.SessionControlService.BackupSession:output_type -> autoforward.BackupSessionResponse
	15, // 38: autoforward.SessionControlService.RestoreSession:output_type -> autoforward.RestoreSessionResponse
	2,  // 39: autoforward.SessionControlService.TerminateSession:output_type -> autoforward.StatusResponse
	22, // 40: autoforward.ForwardRuleControlService.ListRules:output_type -> autoforward.ListRulesResponse
	17, // 41: autoforward.ForwardRuleControlService.CreateRule:output_type -> autoforward.ForwardRule
	17, // 42: autoforward.ForwardRuleControlService.UpdateRule:output_type -> autoforward.ForwardRule
	2,  // 43: autoforward.ForwardRuleControlService.DeleteRule:output_type -> autoforward.StatusResponse
	28, // 44: autoforward.FilterControlService.ListFilters:output_type -> autoforward.ListFiltersResponse
	23, // 45: autoforward.FilterControlService.CreateFilter:output_type -> autoforward.FilterRule
	23, // 46: autoforward.FilterControlService.UpdateFilter:output_type -> autoforward.FilterRule
	2,  // 47: autoforward.FilterControlService.DeleteFilter:output_type -> autoforward.StatusResponse
	34, // 48: autoforward.AIControlService.ListAIConfigs:output_type -> autoforward.ListAIConfigsResponse
	29, // 49: autoforward.AIControlService.CreateAIConfig:output_type -> autoforward.AIConfig
	29, // 50: autoforward.AIControlService.UpdateAIConfig:output_type -> autoforward.AIConfig
	2,  // 51: autoforward.AIControlService.DeleteAIConfig:output_type -> autoforward.StatusResponse
	36, // 52: autoforward.AIControlService.TestAIRewrite:output_type -> autoforward.TestAIRewriteResponse
	38, // 53: autoforward.SystemStatusControlService.GetSystemStats:output_type -> autoforward.SystemStatsResponse
	33, // [33:54] is the sub-list for method output_type
	12, // [12:33] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_autoforward_proto_init() }
func file_autoforward_proto_init() {
	if File_autoforward_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_autoforward_proto_rawDesc), len(file_autoforward_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_autoforward_proto_goTypes,
		DependencyIndexes: file_autoforward_proto_depIdxs,
		EnumInfos:         file_autoforward_proto_enumTypes,
		MessageInfos:      file_autoforward_proto_msgTypes,
	}.Build()
	File_autoforward_proto = out.File
	file_autoforward_proto_goTypes = nil
	file_autoforward_proto_depIdxs = nil
}
